Allow custom folder for SDMC and NAND Directories
citra-emu/citra pull request #5759
Opened 2021-04-10 20:31 UTC by nieldm

This attempts to Fix #3818

2021-04-10 21:14 UTC, B3n30 commented
Thx for the commit.

here are some remarks: 
1. UI changes require some screenshots. 
2. I dont think this should be configurable from the menu, But should be Part of the config dialog
3. Changing those folders should only be possible, when the emulation isnt running or Citra might crash
4. There needs to be some concept about save states, or we might introduce some issues here

2021-04-10 21:26 UTC, nieldm commented
Thx for feedback @B3n30 I will do the changes to cover this points, not sure about the last one.

Just picked up this ticket to start diving into citra's code.

2021-04-13 17:14 UTC, JohelEGP requested changes
I haven't tried this build, only reviewed the code. I notice that sometimes NAND comes first, others SDMC, for otherwise almost equal code.

2021-04-13 17:14 UTC, JohelEGP commented on src/citra_qt/configuration/config.cpp
> +        ReadSetting(QStringLiteral("nand_directory"), QString::fromStdString(nan_dir))
```suggestion
    std::string nand_dir = FileUtil::GetUserPath(FileUtil::UserPath::NANDDir);
    Settings::values.nand_dir =
        ReadSetting(QStringLiteral("nand_directory"), QString::fromStdString(nand_dir))
```

2021-04-17 22:21 UTC, nieldm commented
> Thx for the commit.
> 
> here are some remarks:
> 
> 1. UI changes require some screenshots.
> 2. I dont think this should be configurable from the menu, But should be Part of the config dialog
> 3. Changing those folders should only be possible, when the emulation isnt running or Citra might crash
> 4. There needs to be some concept about save states, or we might introduce some issues here

I just updated the branch solving points 1, 2 and 3, but 4 I feel it's out of my current knowledge of Citra, but I will be glad to learn more about it, could you give me more context and/or point me in the right direction.

2021-04-18 08:00 UTC, B3n30 approved these changes
Looks good to me now. Thanks for the good work.

For 4.: I think #5760 is a big step in the right direction, to solve this issue. Maybe you have a look at it, to see if it is compatible with your changes.

2021-04-18 10:57 UTC, nieldm commented
> #5760

Perfect thx I would take look into it

2021-04-24 05:35 UTC, bunnei approved these changes

2021-04-24 05:35 UTC, merged

2021-06-23 11:03 UTC, zhaowenlan1779 commented
Obviously I am too late, but I have to say ... I hate those two lines. The captialization on the "T" and the period are missing.