gcc 11 compatibility fix (suggestion)
citra-emu/citra pull request #5778
Opened 2021-04-29 09:07 UTC by thesourcehim

I encountered two problems while trying to compile Citra in Fedora 34 using gcc 11.
1. Missing include
2. offsetof macro problem. Looks like in gcc 11 this macro can not be used at runtime anymore, only at compile-time, so runtime variables can not be used as an array subscript. I made a fix for that but it looks a bit clunky. Can someone review it please, may be there's more elegant solution?

2021-04-29 16:51 UTC, JohelEGP commented
Resolves #5776.

2021-04-29 22:05 UTC, BreadFish64 requested changes
Hmm, that is unfortunate. A more appropriate way to solve this would be to use pointer arithmetic. See here for an example: https://godbolt.org/z/czo31oKq6

2021-04-30 14:00 UTC, thesourcehim commented
Just a minute, I think I found another way that doesn't need pointers

2021-04-30 14:09 UTC, thesourcehim commented
Ok, I think that looks better now. Tested with Ocarina of Time and Link between Worlds a little, everything works fine it seems.

2021-04-30 19:22 UTC, vitor-k commented
The CI isn't running because of Github's new policies for new contributors, but you need to run clang-format.
I can open a PR to your branch with the changes if you want to.

2021-05-01 04:01 UTC, thesourcehim commented
Sure. What do I need to do so GitHub allows clang-format to run? Can I run it manually?

2021-05-01 04:50 UTC, vitor-k commented
If you're using Visual Studio, clang format is set up as a project you can manually build, which makes it go over every file.
I think in other OSs you can run clang format directly, I believe we specify clang-format 10.
(Someone from the team will have to enable you CI checks again)

2021-05-01 04:52 UTC, JohelEGP commented
It's clang-format-6: https://github.com/citra-emu/citra/wiki/Contributing#using-clang-format-version-60.

2021-05-01 04:57 UTC, vitor-k commented
That's outdated: https://github.com/citra-emu/citra/blob/edbd6dfe8aad7dd1b626aaf20037d8ede6127bb6/CMakeLists.txt#L264 (see #5500)
I'll change the wiki

2021-05-07 07:28 UTC, thesourcehim commented
So, what should I do next?

2021-05-07 12:32 UTC, BreadFish64 approved these changes

2021-05-07 12:33 UTC, BreadFish64 commented
I doubt this could cause problems but I'll put it in canary for a day or so then merge it.

2021-05-11 03:10 UTC, merged