Request Camera Permission on MacOS
citra-emu/citra pull request #5786
Opened 2021-05-15 22:29 UTC by vitor-k

An attempt to fix #5567.
If this works, supersedes #5568

Starting from macOS 10.14, users need to grant permissions for applications to use media capture (camera and microphone).

The application must provide a description in its Info.plist or it will be terminated due to privacy violation upon attempting to initialize camera/microphone. Applications should also request and check for permission from the user.

Apparently we need to trigger the permission request ourselves. This is done by calling the Objective-c function.
The request should pop up when the "qt" camera option is selected, or when the camera is started.

I have no machine that runs MacOS and thus no way to test this.

I haven't gotten to it yet but requesting for microphone usage should follow the same procedure.

Reference: https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture/requesting_authorization_for_media_capture_on_macos?language=objc

2021-06-20 10:53 UTC, zhaowenlan1779 requested changes

2021-06-20 10:53 UTC, zhaowenlan1779 commented on src/citra_qt/usage_authorization.mm
> +                }];
```suggestion
                [AVCaptureDevice requestAccessForMediaType:media_type completionHandler:^(BOOL granted) {
                    authorized = granted;
                }];
```

Also, this doesn't seem right, as this method doesn't block, and therefore the first call of `CheckAuthorizationForCamera()` will always return false. You either need to make this block (probably with a `Common::Event`), or use some callback mechanic to inform the UI (QtMultimediaCamera) code of the authorization status. Either way, you won't need the static variable `authorized`.

2021-06-20 10:53 UTC, zhaowenlan1779 commented on src/citra_qt/usage_authorization.mm
> +                    LOG_WARNING(Frontend, "Camera access denied. To change this you may modify the macos system settings for Citra at 'System Preferences -> Security & Privacy -> Camera'");
This line is way too long, and this file doesn't really comply with our code style in general. I think we need to set up clang format for Objective-C++.

2022-02-05 09:58 UTC, bunnei approved these changes

2022-02-05 09:58 UTC, merged