Start abstracting the rasterizer cache from OpenGL
citra-emu/citra pull request #6103
Opened 2022-08-21 10:54 UTC by GPUCode

This is a preliminary pull request that aims to dust off the OpenGL backend while at the same time decouple the rasterizer cache from raw OpenGL code. In addition the desktop OpenGL context version is bumped to 4.3 which allows us to remove many extension checks and legacy paths. Textures are now allocated exclusively with glTexStorage* and shadow rendering is always enabled since the presense of the required extensions is guaranteed by both OpenGL ES 3.1 and OpenGL 4.3. Due to this, combined with the updated drivers from AMD, many hacks and legacy paths have been removed. However if need arises they can be reintroduced.

The rasterizer cache sees the biggest changes from the bunch. It has been moved into a separate directory and split into many header files to reduce code clutter and improve readability. Texture operations are now handled by the TextureRuntime instead of the cache itself which simplifies the cache code. All of this is done to make porting other graphics APIs easier.

2022-08-21 18:45 UTC, BreadFish64 requested changes
Nice work 👍
Make sure to run clang-format.

2022-08-21 18:45 UTC, BreadFish64 commented on src/video_core/renderer_opengl/texture_filters/texture_filterer.h
> +public:
Redundant `public`

2022-08-21 18:45 UTC, BreadFish64 commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> -    if ((resolution_scale_factor != VideoCore::GetResolutionScaleFactor()) |
I should've added a comment for this, but this is intentionally _not_ short circuited so that simultaneous resolution and filter changes apply in the same frame.

2022-08-21 18:45 UTC, BreadFish64 commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +            if (surface->pixel_format == PixelFormat::Invalid && surface->type != SurfaceType::Fill) {
Why is checking for Fill no longer applicable here?

2022-08-21 18:50 UTC, GPUCode commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +    const GLsizei levels = static_cast<GLsizei>(std::log2(std::max(width, height))) + 1;
C++ 20 is not enabled with this PR, so I still cannot use the bit header

2022-08-21 18:51 UTC, GPUCode commented on src/video_core/renderer_opengl/gl_rasterizer.cpp
> +                    break;
This code path is reachable, when texture unit 0 has a normal texture. Not having a default case causes a compiler warning so this is just to shut up the warning

2022-08-21 18:53 UTC, GPUCode commented on src/video_core/renderer_opengl/texture_filters/texture_filterer.h
> +public:
This is actually intentional on my part. I like to separate interface from variables in classes by prefix the label, even when it seems redundant. Can remove it if it does not match the codebase style

2022-08-21 18:54 UTC, GPUCode commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +            if (surface->pixel_format == PixelFormat::Invalid && surface->type != SurfaceType::Fill) {
Paper Mario Sticker produces a constant stream of errors that appear to come from this function. The function is finding a fill surface and prints this warning. Fill surfaces don't have their format set, so I assumed this should be accounted for.

2022-08-21 18:56 UTC, GPUCode commented on src/video_core/rasterizer_cache/pixel_format.h
> +inline constexpr std::string_view PixelFormatAsString(PixelFormat format) {
Didn't know that, will take it into account in the future

2022-08-21 19:04 UTC, GPUCode commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> -    if ((resolution_scale_factor != VideoCore::GetResolutionScaleFactor()) |
I'm sorry but I don't understand the reasoning behind this. If the check was dealing with integers I would probably have kept this, but both `resolution_scale_factor != VideoCore::GetResolutionScaleFactor()` and ```
(VideoCore::g_texture_filter_update_requested.exchange(false) &&
         texture_filterer->Reset(Settings::values.texture_filter_name, resolution_scale_factor))
```
are booleans which means this operator is basically equavalent to ||. I even got a compiler warning about it

2022-08-21 19:08 UTC, BreadFish64 commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +            if (surface->pixel_format == PixelFormat::Invalid && surface->type != SurfaceType::Fill) {
I still don't understand. The message is only printed if it finds a non-fill surface with an invalid format.
Fill surfaces have an invalid format because they represent memory fills by the DMA and the format is not applicable afaik. We ignore them in this function because it's possible to revalidate a surface from a fill surface.

2022-08-21 19:17 UTC, GPUCode commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +            if (surface->pixel_format == PixelFormat::Invalid && surface->type != SurfaceType::Fill) {
Ok I will remove this check then. Can anything be done about the errors though?

2022-08-21 19:17 UTC, BreadFish64 commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> -    if ((resolution_scale_factor != VideoCore::GetResolutionScaleFactor()) |
The right side of the `or` has side-effects that must occur even if the left side is true. If you use `||` here and you change the resolution and filter settings, it will change the resolution and flush the cache in one frame, then change the filter and flush the cache in the next.
This is a better way to write it:
```cpp
const bool resolution_scale_changed = resolution_scale_factor != VideoCore::GetResolutionScaleFactor();
const bool texture_filter_changed = VideoCore::g_texture_filter_update_requested.exchange(false)
                      && texture_filterer->Reset(Settings::values.texture_filter_name, VideoCore::GetResolutionScaleFactor());
if (resolution_scale_changed || texture_filter_changed) {
```

2022-08-21 19:21 UTC, GPUCode commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> -    if ((resolution_scale_factor != VideoCore::GetResolutionScaleFactor()) |
So this is basically relying on the fact that with | the compiler with compute both conditions before flushing, while with || it will immediately enter the body of the if, without executing the exchange. Yeah it's not really the best thing to rely on such implicit behaviour, better to do it your proposed way

2022-08-21 19:21 UTC, BreadFish64 commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +            if (surface->pixel_format == PixelFormat::Invalid && surface->type != SurfaceType::Fill) {
If the game is functioning fine then we can probably drop this to a debug log.

2022-08-21 19:26 UTC, GPUCode commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +            if (surface->pixel_format == PixelFormat::Invalid && surface->type != SurfaceType::Fill) {
Sticker Star has been playable for a while now, so I'll drop this to debug

2022-08-21 19:46 UTC, GPUCode commented
Just run clang-format, running the cmake target didn't work so I had to do it manually

2022-08-22 04:23 UTC, BreadFish64 commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +            if (surface->pixel_format == PixelFormat::Invalid && surface->type != SurfaceType::Fill) {
Oh wow my bad, I came back to this and realized I somehow read the diff backward and thought you removed the. Putting `surface->type != SurfaceType::Fill` here was correct and I thought you had removed it.

2022-08-22 05:01 UTC, GPUCode commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +            if (surface->pixel_format == PixelFormat::Invalid && surface->type != SurfaceType::Fill) {
No problem, I added it back

2022-08-22 07:16 UTC, SachinVin commented on src/common/vector_math.h
> +    const T* AsArray() const {
Maybe `Data()` is a better name?

2022-08-22 07:38 UTC, SachinVin commented on src/video_core/renderer_opengl/gl_format_reinterpreter.h
> +    OGLFramebuffer read_fbo, draw_fbo;
nit.. split into its own lines

2022-08-22 07:42 UTC, SachinVin commented on src/video_core/renderer_opengl/gl_format_reinterpreter.cpp
> +    Register(PixelFormat::RGBA8, std::make_unique<ShaderD24S8toRGBA8>());
We might still need to work around intel's broken drivers, microsoft considers them "stable" and ships them by default

2022-08-22 07:46 UTC, SachinVin commented on src/video_core/renderer_opengl/gl_rasterizer.cpp
> +    shader_program_manager = std::make_unique<ShaderProgramManager>(emu_window, true);
Android should have seperable shaders disabled (or optional with default `off`)

2022-08-22 07:48 UTC, SachinVin commented on src/video_core/renderer_opengl/gl_rasterizer.cpp
> +    auto BindCubeFace = [&](GLuint& target, Pica::TexturingRegs::CubeFace face,
```suggestion
    const auto BindCubeFace = [&](GLuint& target, Pica::TexturingRegs::CubeFace face,
```
nit

2022-08-22 07:56 UTC, SachinVin commented on src/video_core/renderer_opengl/gl_shader_util.cpp
> +                                     : "#version 450 core\n";
shouldn't it be `#version 430 core` ?

2022-08-22 07:58 UTC, SachinVin commented on src/video_core/renderer_opengl/texture_downloader_es.cpp
> +#include "video_core/renderer_opengl/texture_downloader_es.h"
Unintended change I assume, `shaders/*` arent actually headers ?

2022-08-22 08:04 UTC, GPUCode commented on src/common/vector_math.h
> +    const T* AsArray() const {
Well there already is a function called AsArray so I think it's better not have two names for functions that do the same thing. The caller can opt into the constness

2022-08-22 08:09 UTC, SachinVin commented on src/common/vector_math.h
> +    const T* AsArray() const {
Right, I did not see the other function.

2022-08-22 13:26 UTC, BreadFish64 approved these changes

2022-08-22 14:36 UTC, Daisouji commented
Clang it.

2022-08-22 15:02 UTC, SachinVin commented
Bumps - 
https://github.com/citra-emu/citra/blob/master/src/video_core/renderer_opengl/renderer_opengl.cpp#L1246
https://github.com/citra-emu/citra/blob/master/src/video_core/renderer_opengl/renderer_opengl.cpp#L1275-L1276
https://github.com/citra-emu/citra/blob/master/src/citra_qt/main.cpp#L919

2022-08-22 20:45 UTC, GPUCode commented
> Bumps - https://github.com/citra-emu/citra/blob/master/src/video_core/renderer_opengl/renderer_opengl.cpp#L1246 https://github.com/citra-emu/citra/blob/master/src/video_core/renderer_opengl/renderer_opengl.cpp#L1275-L1276 https://github.com/citra-emu/citra/blob/master/src/citra_qt/main.cpp#L919

Fixed all suggestions and upgraded glad as well to match the new context version

2022-08-24 00:23 UTC, TheGreatestJannet commented
This PR ups the OpenGL requirement to 4.3 right? If so does this mean you are dropping macOS support? MacOS only supports 4.1.

2022-08-24 07:12 UTC, GPUCode commented
> 

The drop is only temporary until Vulkan is finished

2022-08-25 15:15 UTC, SachinVin commented
https://github.com/citra-emu/citra/blob/master/.github/workflows/ci.yml#L156 removing `macos` should stop publishing macos bins, we can add it back once we have a working build

2022-09-01 18:37 UTC, merged