Added support for Dutch, slightly increased general localisation
citra-emu/citra pull request #6151
Opened 2022-10-05 15:17 UTC by VidalSpierings

- Created localisation for Dutch by adding localised strings.xml file in newly created values-nl map under res and localising arrays.xml file to Dutch

- Slightly improved localisation bij partially localising arrays.xml file to all languages with Latin alphabet that were already localised

2022-10-06 16:37 UTC, Fs00 requested changes
There a few issues in the Italian translation

2022-10-06 16:37 UTC, Fs00 commented on src/android/app/src/main/res/values-it/arrays.xml
> +        <item>Nessuno</item>
```suggestion
        <item>Nessuna</item>
```

2022-10-06 16:37 UTC, Fs00 commented on src/android/app/src/main/res/values-it/arrays.xml
> +        <item>Inversione</item>
```suggestion
        <item>Invertita</item>
```

2022-10-07 14:56 UTC, SachinVin commented
Thanks, but translations are currently managed on transifex, https://explore.transifex.com/citra/citra/ .
Cc: @FearlessTobi

2022-10-07 14:56 UTC, closed without merging