Implement/Fix more SOC related functions
citra-emu/citra pull request #6267
Opened 2023-01-29 19:14 UTC by PabloMK7

This PR implements the following functionality:
 - `SOC_U::GetHostByName`
 - `SOC_U::GetNetworkOpt` (partially)
 - `AC::GetWifiStatus`

Also, this PR fixes the functionality provided by `SOC_U::GetHostId`. The previous implementation returned the first network interface of the machine, which may not be the one exposed to the internet. The new implementation does a connection test to `conntest.nintendowifi.net` to obtain the proper network interface. 

The optimal solution to obtain the right network interface would be to have a promt in the citra settings to ask the user, but in most of the cases, the connection test should be enough (if it is really a problem, it can be implemented in a future PR).

TODO:
- [ ] Test the functionality on Android and Linux

2023-01-29 19:25 UTC, B3n30 commented
Not sure if GetWifiStatus should really report "connected" now, since if networking isn't fully supported this could result in a lot of games that are currently working in crashing, softlocking etc... Maybe it's better to make this configurable?

2023-01-29 19:28 UTC, B3n30 commented on src/core/hle/service/ac/ac.cpp
> +    std::shared_ptr<SOC::SOC_U> socu_module = SOC::GetService(Core::System::GetInstance());
The comment above needs some update, too

2023-01-29 19:28 UTC, B3n30 commented on src/core/hle/service/ac/ac.cpp
> +    rb.Push<u32>(can_reach_internet ? (Settings::values.is_new_3ds ? 2 : 1)
maybe add an enum instead of magic numbers?

2023-01-29 19:28 UTC, B3n30 commented on src/core/hle/service/soc_u.cpp
> +    HostByNameData* hbn_data_ptr =
shouldn't this be a smart/unique pointer?

2023-01-29 19:28 UTC, B3n30 commented on src/core/hle/service/soc_u.cpp
> +    u32 err = 0xffff8025;
this section contains way to many magic numbers

2023-01-29 19:28 UTC, PabloMK7 commented
> Not sure if GetWifiStatus should really report "connected" now, since if networking isn't fully supported this could result in a lot of games that are currently working in crashing, softlocking etc... Maybe it's better to make this configurable?

Can you provide examples? None of the games I have use GetWifiStatus.

2023-01-29 19:32 UTC, GPUCode commented on src/core/hle/service/soc_u.cpp
> +    memset(&hbn_data, 0, sizeof(HostByNameData));
Use std::memset for consistency with the rest of the codebase

2023-01-29 19:32 UTC, GPUCode commented on src/core/hle/service/soc_u.cpp
> +            strncpy(hbn_data.aliases[count], curr, 255);
Ditto for this and the rest of the c functions

2023-01-29 19:32 UTC, GPUCode commented on src/core/hle/service/soc_u.cpp
> +                memcpy(opt_data.data(), std::array<u8, 4>({0, 0, 0, 0}).data(),
You can make this std::array into a constexpr constant with a name to avoid redefining it multiple times

2023-01-29 19:32 UTC, GPUCode commented on src/core/hle/service/soc_u.cpp
> +    if (level == 0xfffe) {
Can these magic number be made into enums/constants. It would help with readability.

2023-01-29 19:35 UTC, B3n30 commented on src/core/hle/service/soc_u.cpp
> +    u32 err = 0xffff8025;
also consider to decode the error code (the nintendo homebrew discord has a tool for it) and construct the error like in the rest of the code

2023-01-29 19:57 UTC, PabloMK7 commented on src/core/hle/service/soc_u.cpp
> +                memcpy(opt_data.data(), std::array<u8, 4>({0, 0, 0, 0}).data(),
This applies to the first commit, as I didn't implement the functionality yet.

2023-01-29 20:07 UTC, PabloMK7 commented on src/core/hle/service/soc_u.cpp
> +    u32 err = 0xffff8025;
The error code is a SOC error code, not a result. In fact, it appears this error code is an odd one and doesn't seem to follow the same values as other SOC error codes.

About the magic values, none of the values in the soc hle implementations have enums. Probably because it isn't completely clear what they do. In any case I've added comments to the code to make them more clear.

2023-01-29 20:08 UTC, PabloMK7 commented on src/core/hle/service/soc_u.cpp
> +    if (level == 0xfffe) {
Refer to https://github.com/citra-emu/citra/pull/6267#discussion_r1090044276

2023-01-30 09:47 UTC, FearlessTobi requested changes

2023-01-30 09:47 UTC, FearlessTobi commented on src/core/hle/service/soc_u.cpp
> +    if (found != sockopt_map.end())
can be braced

2023-01-30 09:47 UTC, FearlessTobi commented on src/core/hle/service/soc_u.cpp
> +    u32 len = rp.Pop<u32>();
A lot of these can be made `const`.

2023-01-30 09:47 UTC, FearlessTobi commented on src/core/hle/service/soc_u.cpp
> +    auto dest_addr_buff = rp.PopStaticBuffer();
```suggestion
    auto dest_addr_buffer = rp.PopStaticBuffer();
```
Dito below

2023-01-30 09:47 UTC, FearlessTobi commented on src/core/hle/service/soc_u.cpp
> +    if (ret == SOCKET_ERROR_VALUE)
can be braced

2023-01-30 09:47 UTC, FearlessTobi commented on src/core/hle/service/soc_u.cpp
> +                    memcpy(opt_data.data(), &interface_info.address, 4);
opt_data should can be a struct here so you don't have to memcpy with magic numbers.

2023-01-30 09:47 UTC, FearlessTobi commented on src/core/hle/service/soc_u.cpp
> +            if (opt_len >= 0xC) {
please don't use magic numbers.

2023-01-30 09:47 UTC, FearlessTobi commented on src/core/hle/service/soc_u.cpp
> +            if (opt_len >= 0x18) {
dito

2023-01-30 09:47 UTC, FearlessTobi commented on src/core/hle/service/soc_u.cpp
> +                LOG_ERROR(Service_SOC, "GetNetworkOpt level={} opt_name={} opt_len>=24 STUBBED",
```suggestion
                LOG_WARNING(Service_SOC, "(STUBBED) called, level={} opt_name={} opt_len >= 24",
```

2023-01-30 09:47 UTC, FearlessTobi commented on src/core/hle/service/soc_u.cpp
> +            LOG_ERROR(Service_SOC, "GetNetworkOpt opt_name={} STUBBED", opt_name);
```suggestion
            LOG_WARNING(Service_SOC, "(STUBBED) called, opt_name={}", opt_name);
```

2023-01-30 09:47 UTC, FearlessTobi commented on src/core/hle/service/soc_u.cpp
> +bool SOC_U::GetDefaultInterfaceInfo(InterfaceInfo* out_info) {
I suggest looking at yuzus implementation of a similar function (https://github.com/yuzu-emu/yuzu/blob/master/src/core/internal_network/network_interface.cpp).

It seems much cleaner in my opinion and doesn't rely on us pinging Nintendos servers.

2023-01-30 09:47 UTC, FearlessTobi commented on src/core/hle/service/soc_u.h
> +        char hName[256];
Can be an `std::array`. Same below.

2023-01-30 14:38 UTC, SachinVin commented on src/core/hle/service/soc_u.cpp
> +    auto found = sockopt_map.find(opt);
```suggestion
    const auto& found = sockopt_map.find(opt);
```

2023-01-30 14:40 UTC, SachinVin commented on src/core/hle/service/soc_u.cpp
> +    HostByNameData& hbn_data = *reinterpret_cast<HostByNameData*>(hbn_data_out.data());
this is UB

2023-02-01 16:16 UTC, PabloMK7 commented on src/core/hle/service/soc_u.cpp
> +bool SOC_U::GetDefaultInterfaceInfo(InterfaceInfo* out_info) {
Yuzu's implementation relies on having the user manually select the interface. This implementation automatically detecs the default interface used to send traffic to the internet, [the same way dolphin does](https://github.com/dolphin-emu/dolphin/blob/2a2ee5d543c054c7880499136fa88d33670f97ec/Source/Core/Core/IOS/Network/IP/Top.cpp#L172). In fact, I tested the Windows implementation from dolphin, but it's not producing the right broadcast address, so I'm sticking to linux implementation for all the platforms. Keep in mind that it's not possible to determine which interface is the default one unless we check the forwarding tables or use a socket to connect to an address. (According to dolphin source, no packet is actually sent through the socket).

In any case, I've switched to `8.8.8.8` as it doesn't require a DNS lookup.

2023-02-14 20:17 UTC, FearlessTobi commented
mingw build is failing.

2023-02-14 20:44 UTC, PabloMK7 commented
> mingw build is failing.

Yes, I've fixed more things and I'll commit shortly

2023-02-26 11:27 UTC, GPUCode approved these changes

2023-02-27 23:06 UTC, FearlessTobi requested changes

2023-04-18 18:46 UTC, PabloMK7 commented on src/core/hle/service/soc_u.cpp
> +    static pollfd ToPlatform(SOC::SOC_U& socu, CTRPollFD const& fd, u8& haslibctrbug) {
Intended, value is RW

2023-04-18 18:47 UTC, PabloMK7 commented on src/core/hle/service/soc_u.cpp
> +        result.revents = Events::TranslateToPlatform(fd.revents, true, unused);
The parameter is a reference, so a temporary variable is needed.

2023-04-18 18:52 UTC, PabloMK7 commented on src/core/hle/service/soc_u.cpp
> +        int platform_data_size = static_cast<int>(platform_data.size());
Cannot make const because of the argument to getsockopt

2023-04-18 18:54 UTC, PabloMK7 commented on src/core/hle/service/ac/ac.cpp
> +    std::shared_ptr<SOC::SOC_U> socu_module = SOC::GetService(Core::System::GetInstance());
The behaviour of the ac module on hw is to initialize the wifi chip, try to connect to wifi using one of the access points saved by the user, and perform a connection test to nintendo servers.

We don't have wifi, not even a wifi abstraction layer as we are doing hle on the socket module directly, so this is the closest we can do to check for an internet connection.

2023-04-18 18:58 UTC, PabloMK7 commented on src/core/hle/service/soc_u.cpp
> +    if (in.size() == sizeof(u8)) {
Nope, otherwise the endianess may get messed up.

2023-04-18 19:03 UTC, PabloMK7 commented on src/core/hle/service/soc_u.cpp
> +    auto senderr = (ret == SOCKET_ERROR_VALUE) ? GET_ERRNO : 0;
Changed to `send_error`. We have to read from errno before doing more socket operations that may change it.

2023-05-16 09:36 UTC, Steveice10 approved these changes

2023-05-19 20:57 UTC, Steveice10 commented on src/core/hle/service/soc_u.cpp
> +bool SOC_U::GetDefaultInterfaceInfo(InterfaceInfo* out_info) {
We’ve discussed this a bit and would definitely rather not be calling out to the internet here, especially every time this function gets called. If other auto detect methods aren’t possible then the yuzu method would be preferred.

2023-05-22 02:01 UTC, merged