Rasterizer cache refactor - Custom texture rewrite
citra-emu/citra pull request #6375
Opened 2023-03-27 13:45 UTC by GPUCode

Behold part 2 of the vulkan PR is finally here! It reworks large parts of the rasterizer cache to improve code quality, performance and compatibility with other graphics API like vulkan. The first commit removes the custom texture code which prevents refactor and the final commit of the PR will re-add the new implementation.
We should not tag this for canary until the bellow checklist is complete. The changes might seem a lot but it's almost impossible to separate them into different PRs and the commits themselves, I believe, sufficiently document them. Thus it is recommended, like before, to review them individually. Here are more details about the included changes:

- Reworked surface upload and download code

The previous code was split in two methods LoadGLBuffer/UploadGLTexture, was quite hacky and hard to comprehend as it tried to handle every possible case. This PR refactors that to be much easier to read. MemoryRef is used for automatic bounds checking, format convertions are handled in the new texture_codec header, which also deals with texture formats that previously were very [badly](https://github.com/citra-emu/citra/blob/master/src/video_core/rasterizer_cache/cached_surface.cpp#L110) handled. The runtime is the sole provider of staging memory which should reduce memory usage. I've also tried to mimic modern APIs more so uploads/downloads are submitted using a BufferTextureCopy structure which is filled by the cache with all the necessary information.

Texture downloads have been refactored as well. Previously glReadPixels was the sole option for readbacks, which can be very slow at times. A new function DownloadWithoutFbo is introduced which attemps to readback without using an fbo either with glGetTextureSubImage (available on the vast majority of recent drivers) or using glGetTexImage with full downloads.

Instead of using OGLTexture directly the concenpt of an "Allocation" is used which may contain more than one texture. For example with scaled uploads/downloads the cache would previously [lookup](https://github.com/citra-emu/citra/blob/master/src/video_core/rasterizer_cache/cached_surface.cpp#L313) for a temporary texture and proceed to discard it without recycling it. Allocations contain both scaled and unscaled handles to avoid a round-trip to the cache. This shouldn't have an impact in memory usage due to another change discussed below.

- Texture runtime interface changes

In order to mimic modern APIs better the runtime uses different structures for copying/blitting/buffer copying.

CachedSurface is split into two objects, SurfaceBase which contains the backend agnostic code and Surface which is the backend side implementation. The cache directly makes use of the OpenGL version for now but when we switch to templates the opengl dependency will get completely removed.

- Multi-level surfaces

Mipmaps have always been a pain point. They required an expensive tree like structure with watchers to maintain and properly sync. In addition, every surface allocated an excessive amount of mipmaps which increased memory usage quite a bit, especially when texture filtering was used. Custom textures also suffered from many bugs due to them; there were no checks in place to prevent mipmaps from being larger than the base level and without any indication by the dumper, pack creators often upscaled mips too much. This lay undetected because the cache would also totally ignore custom mipmaps for some reason.

With this change surfaces can now own the entire mipmap range allowing the cache to directly upload and use mipmaps without needing to sync them with watchers. Most SurfaceParams calls are mipmap aware and will detect the mipmap of provided intervals. Surfaces only allocate the amount of levels requested by the game, saving memory. ValidateSurfaces clamps intervals to each level; clamping the interval set itself is also possible but extermely expensive as it showed up while profiling on android. Bonus; by using native mimaps directly this also adds support for mipmap for cube, removing the need for the hack introduced in #3910 . Render to mipmap is also supported by forwarding the mipmap configuration to the framebuffer, but since this is quite an uncommon usecase I don't expect this to be used all the often.

However with the removal of surface watchers, texture cube tracking is a problem. There is no guarantee of memory arrangement for cubes (games can give six random addresses to unit 0 and instruct it to construct a cube). To work around this a new invalidation tracking method is introduced; each time an interval is inserted/erased from invalid_regions a modification tick is incremented. The cube stores pointers to each of the faces as well as the last known ticks. If the tick changes the face is synced.

- OpenGL optimizations

The backend does some inefficient things that really hurt performance on the mali driver. This PR takes the time to correct some of these, significantly improving performance on these gpus (still not full speed in most games but almost 2x improvement than before).

1. Render FBOs are cached and only swapped when their attachments change. The previous code would always call glFramebufferTexture2D in the draw function to update the attachments which killed performance. Other drivers like intel's also recommend the immutable fbo approach so it should be better for everyone.

2. The cache makes more use of texture copies with glCopyImageSubData instead of blitting which should be much more efficient on most drivers.

3. The stream buffer has been rewritten to use synching instead of orphaning. The latter _could_ be more efficient in some cases but profiling has shown that even on excellent drivers like nvidia's it takes a significant amount of time due to reallocations in the driver. On mobile GL_EXT_buffer_storage is used when supported to utilize persistent mappings, improving performance as well.

4. Texture buffer limits are properly respected. Older Mali GPUs only [support](https://forums.unrealengine.com/t/opengl-es-texture-buffer-issues/242699) up to a 64KB range of addressable texels for each texture buffer. Citra would go way above this limit causing weird behaviour. MMJ hadcods this as a [magic](https://github.com/weihuoya/citra/blob/master/src/video_core/renderer_opengl/gl_rasterizer.cpp#L51) value but we do it the proper way here.

5.  Ports @Steveice10 lod bias patch, so GLES can properly emulate it.

- Custom texture rewrite (TBA)

This PR will also rewrite custom textures from the ground up to utilize the new frameworks and changes introduced by this PR . It's not finished yet but very close to completation so, I'll also detail the coming changes.

The multi-surface change was required for this in order to avoid the old mipmap shenanigans. The new mipmap handling is disabled for older packs to avoid crashes but new packs will be required properly provide them. The dumper will have a _mip postfix to indicate to pack creators that a texture is a mip.

New features include support for various file formats like DDS/KTX and compressed formats like BC7/BC5/ASTC etc. The BC* formats are not supported on mobile but we could use the bcn enabler provided by adrenotools in the future for this purpose. Async texture loading will also be supported to completely eliminate loading stutters which are badTM. Texture filtering with custom textures should also work as expected. A new hotkey will also be added to toggle between sd and hd textures without restarting the game. Material map support is planned but not an immediate goal.

"New packs" will be identified by a simple pack.json file which contains information about it such as name, author etc and some configuration options like whether the textures are pre-flipped (allows citra to save some time decoding png files). This is still a work in progress so suggestions are welcome about how this should work without breaking compatibility with older packs

Fixes to do [...]

2023-03-27 22:03 UTC, FearlessTobi reviewed
I cannot comment on the OpenGL code, as I have no experience with GPU programming.

2023-03-27 22:03 UTC, FearlessTobi commented on src/video_core/renderer_opengl/texture_filters/anime4k/anime4k_ultrafast.cpp
> +    const auto setup_temp_tex = [this, src_rect = blit.src_rect](GLint internal_format,
the reference is removed here. is this intentional?

2023-03-30 18:27 UTC, GPUCode commented on src/video_core/renderer_opengl/texture_filters/anime4k/anime4k_ultrafast.cpp
> +    const auto setup_temp_tex = [this, src_rect = blit.src_rect](GLint internal_format,
Not really but taking a reference was unnecessary here since the rectangle is a small structure

2023-04-01 09:10 UTC, SachinVin commented on src/common/memory_ref.h
> +        return std::span{cptr, size > csize ? csize : size};
could've been std::min(size, csize)?

2023-04-01 09:35 UTC, SachinVin commented on src/video_core/CMakeLists.txt
> +target_include_directories(video_core PRIVATE ${HOST_SHADERS_INCLUDE})
Should this be in the host shaders' CMakeLists ?

2023-04-01 09:41 UTC, SachinVin commented on src/video_core/rasterizer_cache/framebuffer_base.cpp
> +                                 SurfaceBase* const depth_stencil, u32 depth_level,
```suggestion
FramebufferBase::FramebufferBase(const Pica::Regs& regs, const SurfaceBase* const color, u32 color_level,
                                 const SurfaceBase* const depth_stencil, u32 depth_level,
```

2023-04-01 09:45 UTC, SachinVin commented on src/video_core/rasterizer_cache/pixel_format.cpp
> +    switch (format) {
can probably be simplified like this - https://github.com/citra-emu/citra/blob/master/src/video_core/renderer_opengl/gl_driver.cpp#L15

2023-04-01 09:49 UTC, SachinVin commented on src/video_core/rasterizer_cache/pixel_format.h
>      Invalid = 255,
Should be updated to UINT_MAX

2023-04-01 09:56 UTC, SachinVin commented on src/video_core/rasterizer_cache/pixel_format.h
> +constexpr std::array<u8, PIXEL_FORMAT_COUNT> BITS_PER_BLOCK_TABLE = {{
Maybe consider something like this https://github.com/citra-emu/citra/blob/master/src/core/hle/service/service.cpp#L59

2023-04-01 10:10 UTC, SachinVin commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +    if (src_surface == nullptr) {
```suggestion
    if (!src_surface) {
```

2023-04-01 10:14 UTC, SachinVin commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +    src_params.end = src_params.addr + src_params.size;
Can be simplifies to initialize like how it's done for `texture_copy`

2023-04-01 10:16 UTC, SachinVin commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +    if (output_gap != 0 &&
Maybe add a comment for what this is checking

2023-04-01 10:19 UTC, SachinVin commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +        return false;
```suggestion
    if (!src_surface) {
        return false;
    }
```

2023-04-01 10:20 UTC, SachinVin commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +    std::memcpy(&fill_surface->fill_data[0], &config.value_32bit, 4);
```suggestion
    std::memcpy(&fill_surface->fill_data[0], &config.value_32bit, sizeof(u32));
```

2023-04-01 10:23 UTC, SachinVin commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +    Surface fill_surface = std::make_shared<OpenGL::Surface>(runtime, params);
LHS should be shared pointer

2023-04-01 10:31 UTC, SachinVin commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +                                        bool load_if_create) -> SurfaceRect_Tuple {
why change the return type ?

2023-04-01 10:43 UTC, GPUCode commented on src/video_core/CMakeLists.txt
> +target_include_directories(video_core PRIVATE ${HOST_SHADERS_INCLUDE})
I think it's better here cause it involves the video_core target

2023-04-01 10:46 UTC, GPUCode commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +    src_params.end = src_params.addr + src_params.size;
Can you elaborate on how to do that? The only extra call here is the UpdateParams at the end, isn't it simple enough?

2023-04-01 10:46 UTC, GPUCode commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +    Surface fill_surface = std::make_shared<OpenGL::Surface>(runtime, params);
It's already a shared pointer. Basically Surface = std::shared_ptr<OpenGL::Surface>

2023-04-01 10:47 UTC, GPUCode commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +                                        bool load_if_create) -> SurfaceRect_Tuple {
The return type is the same, SurfaceRect_Tuple. It was moved after the function definition because the type is a private rasterizer cache member so one would have to write RasterizerCache::SurfaceRect_Tuple which I find more verbose compared to this

2023-04-01 11:44 UTC, SachinVin commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +    Surface fill_surface = std::make_shared<OpenGL::Surface>(runtime, params);
Maybe call it SurfacePtr then, or better yet consider not hiding pointers this way.

2023-04-01 11:49 UTC, SachinVin commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +                                        bool load_if_create) -> SurfaceRect_Tuple {
`RasterizerCache::SurfaceRect_Tuple` tells you the function has access to members of the `RasterizerCache`, otherwise one would assume the function is part of the namespace and not the class

2023-04-01 11:56 UTC, GPUCode commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +    Surface fill_surface = std::make_shared<OpenGL::Surface>(runtime, params);
Tbf this is only temporary, next PR will remove shared_ptr usage for surfaces. The name is still Surface to keep the diff to a minimum as well, Surface is used a lot inside the rasterizer cache so it will be blown up if the name changes. However if you still believe it's better I can rename it

2023-04-01 11:59 UTC, GPUCode commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +                                        bool load_if_create) -> SurfaceRect_Tuple {
At the end of day I don't really think it matter too much if the types are defined globally or inside the cache, the latter is better because they aren't used outside of it though. So should I change it to RasterizerCache::SurfaceRect_Tuple or do you have any other proposal on how to handle this?

2023-04-01 13:03 UTC, SachinVin commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +    src_params.end = src_params.addr + src_params.size;
I meant this way, is there a technical term for it ?
```
    SurfaceParams src_params = {
        .addr = config.GetPhysicalInputAddress();
        .stride = input_width + input_gap; // stride in bytes
        .width = input_width;              // width in bytes
        .height = copy_size / input_width;
        .size = ((src_params.height - 1) * src_params.stride) + src_params.width;
        .end = src_params.addr + src_params.size;
    };
```

2023-04-01 13:08 UTC, GPUCode commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +    src_params.end = src_params.addr + src_params.size;
Oh you mean using designated initializers? That would be possible yes but wouldn't it be very inconsistent to use them in AccelerateTextureCopy only, given that all other usages of SurfaceParams don't? I believe this is something for a dedicated PR to tackle if it's something we want to pursue

2023-04-01 13:11 UTC, SachinVin commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +    Surface fill_surface = std::make_shared<OpenGL::Surface>(runtime, params);
I do think it would be easier to read if it was SurfacePtr, it is quite jarring at first glance. I think most place that use `Surface` are already port of the diff.

2023-04-01 13:20 UTC, GPUCode commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +    Surface fill_surface = std::make_shared<OpenGL::Surface>(runtime, params);
Alright, do you mind if it's renamed to SurfaceRef instead of SurfacePtr, the former looks cleaner to me

2023-04-01 14:58 UTC, GPUCode commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +    u32 copy_size = Common::AlignDown(config.texture_copy.size, 16);
Added a comment about this

2023-04-02 07:19 UTC, SachinVin commented on src/video_core/CMakeLists.txt
>  target_include_directories(video_core PRIVATE ${CMAKE_CURRENT_BINARY_DIR})
can probably be removed

2023-04-02 07:20 UTC, SachinVin commented on src/video_core/rasterizer_cache/pixel_format.h
> +    MaxPixelFormat = 18,
We use `Count` in most places

2023-04-02 07:22 UTC, GPUCode commented on src/video_core/CMakeLists.txt
>  target_include_directories(video_core PRIVATE ${CMAKE_CURRENT_BINARY_DIR})
Why? The add_dependencies ensures host_shaders is built before video_core and the target_include_directories add the necessary includes

2023-04-02 07:23 UTC, GPUCode commented on src/video_core/rasterizer_cache/pixel_format.h
> +    MaxPixelFormat = 18,
Could you provide an example? This isn't used directly anyway, it is aliased to PIXEL_FORMAT_COUNT below

2023-04-02 07:40 UTC, SachinVin commented on src/video_core/rasterizer_cache/pixel_format.h
> +    MaxPixelFormat = 18,
https://github.com/citra-emu/citra/blob/041252ba368e476d924089096acacd6536842828/src/citra_qt/game_list.h#L54
https://github.com/citra-emu/citra/blob/master/src/common/logging/log.h#L34
https://github.com/citra-emu/citra/blob/master/src/common/logging/log.h#L115

2023-04-02 07:45 UTC, GPUCode commented on src/video_core/rasterizer_cache/pixel_format.h
> +    MaxPixelFormat = 18,
Thanks, I will adjust it accordingly

2023-04-02 07:51 UTC, SachinVin commented on src/video_core/rasterizer_cache/pixel_format.h
> +constexpr u32 GetBytesPerPixel(PixelFormat format) {
```suggestion
constexpr u32 GetFormatBytesPerPixel(PixelFormat format) {
```
to make it consistent with the other functions

2023-04-02 08:07 UTC, SachinVin commented on src/video_core/renderer_opengl/texture_filters/texture_filter_base.h
> +enum class SurfaceType : u32;
unused forward decl

2023-04-02 08:15 UTC, SachinVin commented on src/video_core/renderer_opengl/gl_texture_runtime.h
> +    bool HasAttachment(VideoCore::SurfaceType type) const noexcept {
```suggestion
    [[nodiscard]] bool HasAttachment(VideoCore::SurfaceType type) const noexcept {
```

2023-04-02 08:18 UTC, SachinVin commented on src/video_core/renderer_opengl/gl_texture_runtime.h
> +    Driver* driver;
cant we use a reference?

2023-04-02 08:18 UTC, SachinVin commented on src/video_core/renderer_opengl/gl_texture_runtime.h
> +    Driver& driver;
```suggestion
    const Driver& driver;
```

2023-04-02 08:20 UTC, SachinVin commented on src/video_core/renderer_opengl/gl_texture_runtime.h
> +    bool Matches(u32 width_, u32 height_, u32 levels_, const FormatTuple& tuple_) const {
operator== ?

2023-04-02 08:29 UTC, SachinVin commented on src/video_core/renderer_opengl/renderer_opengl.cpp
> +bool HasDebugTool() {
This is probably better in gl_driver

2023-04-02 08:30 UTC, GPUCode commented on src/video_core/renderer_opengl/gl_texture_runtime.h
> +    Driver* driver;
No because the surface needs to be trivially moveable for when shared_ptr is removed

2023-04-02 08:34 UTC, SachinVin commented on src/video_core/renderer_opengl/gl_texture_runtime.cpp
> +    handle = framebuffer.handle;
handle is already set on line 560

2023-04-02 08:36 UTC, SachinVin commented on src/video_core/renderer_opengl/gl_texture_runtime.cpp
> +    glBindFramebuffer(GL_DRAW_FRAMEBUFFER, old_fbo);
IMO this should be inside SCOPE_EXIT after 562

2023-04-02 08:36 UTC, GPUCode commented on src/video_core/renderer_opengl/gl_texture_runtime.cpp
> +    handle = framebuffer.handle;
Both of these are needed. Line 560 is when the framebuffer already exists and this is when it's first created, otherwise the first time it's used the handle won't be set properly

2023-04-02 08:39 UTC, SachinVin commented on src/video_core/renderer_opengl/gl_texture_runtime.cpp
> +    glPixelStorei(GL_PACK_ROW_LENGTH, 0);
Consider moving into a SCOPE_EXIT

2023-04-02 08:41 UTC, GPUCode commented on src/video_core/renderer_opengl/gl_texture_runtime.cpp
> +    glPixelStorei(GL_PACK_ROW_LENGTH, 0);
I personally don't really like SCOPE_EXIT, it's more verbose than just calling the function at the end

2023-04-02 08:41 UTC, SachinVin commented on src/video_core/renderer_opengl/gl_texture_runtime.cpp
> +
```suggestion
    } else {
        UNREACHABLE();
    }

```

2023-04-02 08:42 UTC, GPUCode commented on src/video_core/renderer_opengl/gl_texture_runtime.h
> +    bool Matches(u32 width_, u32 height_, u32 levels_, const FormatTuple& tuple_) const {
imo the equality operator, if it exists, should check if two allocation are the same (their handles are the same). This function checks only if they are compatible from the user perspective so I thought it's better to give it a distinct name

2023-04-02 08:59 UTC, SachinVin commented on src/video_core/renderer_opengl/gl_texture_runtime.h
> +class Surface : public VideoCore::SurfaceBase {
Having more than a single level of inheritance is abstracting a lot here, consider not inheriting SurfaceBase from SurfaceParams

2023-04-02 09:09 UTC, SachinVin commented on src/video_core/renderer_opengl/gl_stream_buffer.cpp
> +        pointer = (u8*)glMapBufferRange(gl_target, iterator, size,
reinterpret_cast

2023-04-02 09:10 UTC, SachinVin commented on src/video_core/renderer_opengl/gl_stream_buffer.h
> +    static constexpr std::size_t SYNC_POINTS = 16;
```suggestion
    static constexpr std::size_t MAX_SYNC_POINTS = 16;
```
maybe makes more sense ?

2023-04-02 09:12 UTC, SachinVin commented on src/video_core/renderer_opengl/gl_stream_buffer.cpp
> +            (u8*)glMapBufferRange(gl_target, 0, buffer_size,
reinterpret_cast

2023-04-02 09:27 UTC, SachinVin commented on src/video_core/renderer_opengl/gl_format_reinterpreter.h
> +    GLint dst_size_loc{-1}, src_size_loc{-1}, src_offset_loc{-1};
Split into multiple lines

2023-04-02 09:27 UTC, SachinVin commented on src/video_core/renderer_opengl/gl_format_reinterpreter.h
> +    GLint dst_size_loc{-1}, src_size_loc{-1}, src_offset_loc{-1};
ditto

2023-04-02 09:31 UTC, SachinVin commented on src/video_core/regs_texturing.h
> +        MaxTextureFormat = 14,
```suggestion
        Count = 14,
```

2023-04-02 09:35 UTC, SachinVin commented on src/video_core/regs_framebuffer.h
> +    bool IsShadowRendering() const {
```suggestion
    [[nodiscard]] bool IsShadowRendering() const {
```

2023-04-02 09:36 UTC, SachinVin commented on src/video_core/regs_framebuffer.h
> +    bool HasStencil() const {
```suggestion
    [[nodiscard]] bool HasStencil() const {
```

2023-04-02 09:38 UTC, SachinVin commented on src/video_core/rasterizer_cache/utils.cpp
> +    UNREACHABLE();
use UNIMPLEMENTED for unimplemented code

2023-04-02 10:01 UTC, GPUCode commented on src/video_core/renderer_opengl/gl_texture_runtime.h
> +class Surface : public VideoCore::SurfaceBase {
SurfaceBase uses a lot of SurfaceParams attributes, especially in GetCopyableInterval. It would be a ton of work to remove that depedency

2023-04-02 12:01 UTC, SachinVin commented on src/video_core/renderer_opengl/gl_texture_runtime.h
> +    Driver* driver;
Then they could be const pointers

2023-04-02 12:02 UTC, SachinVin commented on src/video_core/CMakeLists.txt
>  target_include_directories(video_core PRIVATE ${CMAKE_CURRENT_BINARY_DIR})
target_include_directories(video_core PRIVATE ${CMAKE_CURRENT_BINARY_DIR}) shouldn't be needed since the other target_include_directories should already be handling the host shaders

2023-04-02 12:03 UTC, SachinVin commented on src/video_core/renderer_opengl/gl_texture_runtime.h
> +    bool Matches(u32 width_, u32 height_, u32 levels_, const FormatTuple& tuple_) const {
Gotcha

2023-04-02 12:10 UTC, GPUCode commented on src/video_core/CMakeLists.txt
>  target_include_directories(video_core PRIVATE ${CMAKE_CURRENT_BINARY_DIR})
Oh yeah that one can be removed, nice catch

2023-04-02 12:11 UTC, SachinVin commented on src/video_core/renderer_opengl/gl_texture_runtime.cpp
> +    handle = framebuffer.handle;
I think Line 552 is when the framebuffer already exists, Line 560 is never used after it is set, and it is set again at Line 597.

2023-04-02 12:17 UTC, SachinVin commented on src/video_core/renderer_opengl/gl_texture_runtime.cpp
> +    glPixelStorei(GL_PACK_ROW_LENGTH, 0);
SCOPE_EXIT would allow for early return inside `if (has_sub_image)`

2023-04-02 12:39 UTC, GPUCode commented
Just pushed the new custom texture implementation. The line count seems scary but 2k of these are just from the dds-kth header

2023-04-02 12:57 UTC, SachinVin commented
Can it be a different PR so they can be tested independently?

2023-04-02 12:59 UTC, GPUCode commented
> Can it be a different PR so they can be tested independently?

I can separate it yes, however this one will need to be merged first and I'm afraid that the temporary removal of custom textures will cause a bit of a havoc.

2023-04-03 18:03 UTC, GPUCode commented on src/video_core/renderer_opengl/gl_texture_runtime.cpp
> +    handle = framebuffer.handle;
Checked the code again and you're correct.

2023-04-03 19:22 UTC, GPUCode commented on src/video_core/renderer_opengl/gl_texture_runtime.h
> +class Surface : public VideoCore::SurfaceBase {
I feel like this isn't something that can be easily accomplished now, so I'm resolving this. If you disagree feel free to reopen

2023-04-07 04:58 UTC, SachinVin commented on src/video_core/rasterizer_cache/pixel_format.cpp
> +    switch (format) {
do you intend to change this?

2023-04-07 05:09 UTC, GPUCode commented on src/video_core/rasterizer_cache/pixel_format.cpp
> +    switch (format) {
It was initially in FORMAT_MAP but I changed it back to be consistent with the CustomPixelFormatAsString method for custom pixel formats.

2023-04-07 07:53 UTC, SachinVin commented on src/video_core/rasterizer_cache/pixel_format.cpp
> +    switch (format) {
Alright

2023-04-17 15:49 UTC, BreadFish64 requested changes

2023-04-17 15:49 UTC, BreadFish64 commented on src/video_core/rasterizer_cache/pixel_format.h
> +    {SurfaceType::DepthStencil, 32, 4},
Would be nice to have the pixel format names as comments at the ends of the lines.
Does this give the same results as the old functions? I think the 4-bit formats would return 0 for byte per pixel... although that's questionably useful.

2023-04-17 15:49 UTC, BreadFish64 commented on src/video_core/renderer_opengl/gl_texture_runtime.h
> +    bool NeedsConvertion(VideoCore::PixelFormat pixel_format) const;
```suggestion
    bool NeedsConversion(VideoCore::PixelFormat pixel_format) const;
```

2023-04-17 15:49 UTC, BreadFish64 commented on src/video_core/rasterizer_cache/rasterizer_cache.h
> -    std::recursive_mutex mutex;
Are we getting rid of async GPU?

2023-04-17 15:49 UTC, BreadFish64 commented on src/video_core/rasterizer_cache/texture_codec.h
> +                if constexpr (is_4bit) {
Probably want to static_assert if it tries to encode ETC.

2023-04-17 16:20 UTC, GPUCode commented on src/common/color.h
> +    return (static_cast<u32>(color.r()) + color.g() + color.b()) / 3;
Wouldn't that reduce accuracy? It doesn't really matter though cause this only used in I4 [encoding](https://github.com/GPUCode/citra/blob/c9942b35bb9987e5e152bdfdcf57b327a5703105/src/video_core/rasterizer_cache/texture_codec.h#L187) where all components are always the same.

2023-04-17 16:23 UTC, GPUCode commented on src/video_core/rasterizer_cache/framebuffer_base.cpp
> +        static_cast<s32>(surfaces_rect.bottom + (regs.rasterizer.scissor_test.y2 + 1) * res_scale);
surfaces_rect is already scaled I believe. This has also been taken directly from the [previous](https://github.com/citra-emu/citra/blob/89db2e323adb8e577fcdeef6e4a0ac40f03f187f/src/video_core/renderer_opengl/gl_rasterizer.cpp#L494) code.

2023-04-17 16:24 UTC, GPUCode commented on src/video_core/rasterizer_cache/pixel_format.h
> +    {SurfaceType::DepthStencil, 32, 4},
Yes it does, the old [function](https://github.com/citra-emu/citra/blob/89db2e323adb8e577fcdeef6e4a0ac40f03f187f/src/video_core/rasterizer_cache/pixel_format.h#L189) would return 4 for all texture formats.

2023-04-17 16:25 UTC, GPUCode commented on src/video_core/rasterizer_cache/rasterizer_cache.h
> -    std::recursive_mutex mutex;
It never existed on mainline citra builds and sachin's PR has been closed for a while. I don't think there are plans to bring it back

2023-04-17 16:26 UTC, GPUCode commented on src/video_core/rasterizer_cache/texture_codec.h
> +                if constexpr (is_4bit) {
It won't reach this point if ETC is used, instead it will error out [here](https://github.com/GPUCode/citra/blob/16dd08255a47a85ed8a1011992cd34e406dcc508/src/video_core/rasterizer_cache/utils.cpp#L71)

2023-04-17 17:03 UTC, BreadFish64 commented on src/common/color.h
> +    return (static_cast<u32>(color.r()) + color.g() + color.b()) / 3;
It'd be more accurate if this was just a general purpose function, but yeah, it shouldn't matter here if the components are all the same... But then shouldn't we just take one of the components instead of averaging them?

2023-04-17 17:04 UTC, BreadFish64 commented on src/video_core/rasterizer_cache/framebuffer_base.cpp
> +        static_cast<s32>(surfaces_rect.bottom + (regs.rasterizer.scissor_test.y2 + 1) * res_scale);
Ah hmm, might check this out more in-depth after this is merged then.

2023-04-17 18:45 UTC, BreadFish64 commented on src/video_core/renderer_opengl/gl_format_reinterpreter.cpp
> +    if (use_texture_view) {
nit: Just release unconditionally

2023-04-17 19:26 UTC, GPUCode commented on src/video_core/host_shaders/texture_filtering/scale_force.frag
> +//? #version 320 es
Uh but doesn't LoadShader add the version header to the beginning of the shader? I don't think there's any way to have the precision statement at the top

2023-04-17 19:44 UTC, GPUCode commented on src/video_core/host_shaders/texture_filtering/scale_force.frag
> +//? #version 320 es
Ah, I'm using Qt Creator and there doesn't seem to be any difference in the placement of it

2023-04-17 20:59 UTC, GPUCode commented on src/common/color.h
> +    return (static_cast<u32>(color.r()) + color.g() + color.b()) / 3;
This code was written by @Steveice10 so they probably know more on why this is useful.

2023-04-17 21:01 UTC, Steveice10 commented on src/common/color.h
> +    return (static_cast<u32>(color.r()) + color.g() + color.b()) / 3;
We probably could just take one component for our use case if you prefer, it was written to be a general purpose RGB to I conversion.

2023-04-17 21:09 UTC, GPUCode commented on src/common/color.h
> +    return (static_cast<u32>(color.r()) + color.g() + color.b()) / 3;
Eh I personaly say we leave it as is, it's a pretty minor change

2023-04-17 21:25 UTC, BreadFish64 commented on src/common/color.h
> +    return (static_cast<u32>(color.r()) + color.g() + color.b()) / 3;
Another thing to consider: If this is intended to be general purpose then do we really want an average, or do we want it to be perceptually accurate. I'd personally do a fixed point calculation for Rec709 luminance.

2023-04-17 21:46 UTC, GPUCode commented on src/video_core/host_shaders/texture_filtering/scale_force.frag
> +//? #version 320 es
It doesn't look quite right with the version on the top and the copyright below. This is highly editor dependant too, so I'll mark this as addressed. If you believe this should definitely be done, feel free to reopen.

2023-04-17 21:53 UTC, GPUCode commented on src/video_core/rasterizer_cache/rasterizer_cache.cpp
> +                                        bool load_if_create) -> SurfaceRect_Tuple {
Removed the trailing returns

2023-04-17 22:44 UTC, BreadFish64 approved these changes

2023-04-18 11:12 UTC, GPUCode commented
Will merge in a few hours if no more reviews

2023-04-21 07:14 UTC, merged