Trying to add cheats to configuration per game
citra-emu/citra pull request #6379
Opened 2023-03-28 19:14 UTC by luc-git

Hello with my pull request you can add cheat with per game property but the problem is that it only works if a game is running.
If it's doesn't the case citra will crash with an access violation exception nullptr. So this pointer will point to the running game if I understand.

2023-03-28 19:17 UTC, SleepingSnakezzz commented
Sorry, I don't understand the point of this. If the cheat codes can only be added whilst the game is launched (just like the normal cheats menu), then all you've done here is add extra steps to accessing the same cheats menu that users can already access by `Emulation>Cheats`.

2023-03-28 19:17 UTC, luc-git commented
Yes of course but I think it would be a good idea to add cheats when a game is not running

2023-03-28 19:18 UTC, luc-git commented
It could be possible because other emulators can do this way

2023-03-28 20:12 UTC, FearlessTobi requested changes
I see no benefit from this, if it introduces no new functionality.
As Snake said, Cheats already can be configured when a game is running.

2023-03-28 20:16 UTC, luc-git commented
Yes this is the problem of the cheats configuration it only works if a game is running

2023-03-28 20:56 UTC, SleepingSnakezzz commented
Then the appropriate way to suggest this is to open a feature request in our Github's issues section. Opening a PR with a non-functional change does not help.

2023-03-29 11:34 UTC, GPUCode commented
I think this PR has merit, cheats should ideally go to the per-game menu. But the crashing issue needs to be fixed first. Consider disabling the tab if the menu is opened without a game running.

2023-03-31 20:15 UTC, GPUCode requested changes
While the Qt code looks fine, duplicating the cheat management functions in the GUI side isn't the correct solution here. This results in having two different implementations that do the same thing.

2023-03-31 20:16 UTC, luc-git commented
So can I remove functions from the core side?

2023-03-31 20:17 UTC, luc-git commented
If I use the core part there is an access violation

2023-03-31 20:26 UTC, luc-git commented
You need to execute this line https://github.com/citra-emu/citra/blob/master/src/core/core.cpp#L312 to prevent the accessviolation.
But if I want to pass this  https://github.com/citra-emu/citra/blob/master/src/citra_qt/main.cpp#L2593 it will not work

2023-03-31 20:26 UTC, luc-git commented
Maybe we need to pass the pointer

2023-03-31 20:49 UTC, GPUCode commented
My suggestion; add a constructor to System and move the creation of CheatEngine there. Then update LoadCheatFile and SaveCheatFile to receive the program_id instead of taking it from system directly. Downside is that this requires quite a bit of work updating CheatDialog and android to account for that but I believe it's the best solution.
Maybe wait until another developer can suggest something else, someone could have a simpler idea

2023-03-31 20:52 UTC, luc-git commented
Can program_id have a value even if a game is not running?

2023-03-31 20:54 UTC, GPUCode commented
It does not, but the per game dialog has access to the program id of the game being configured, which is why the cheat engine needs to be modified to receive it

2023-04-01 21:40 UTC, luc-git commented
> While the Qt code looks fine, duplicating the cheat management functions in the GUI side isn't the correct solution here. This results in having two different implementations that do the same thing.

Fixed

2023-04-05 20:41 UTC, GPUCode reviewed
Looks good overall now, great job!

2023-04-05 20:41 UTC, GPUCode commented on src/citra_qt/cheats.cpp
> +    if (edited)
Add braces

2023-04-05 20:41 UTC, GPUCode commented on src/citra_qt/configuration/configure_per_game.cpp
> +    if (cheat_tab->ApplyConfiguration())
Ditto for braces

2023-04-05 20:41 UTC, GPUCode commented on src/core/cheats/cheats.cpp
> +    if (Core::System::GetInstance().KernelRunning())
```suggestion
    if (system.IsPoweredOn())
```

2023-04-14 22:05 UTC, luc-git commented
Changes are resolved any news?

2023-04-14 23:54 UTC, SleepingSnakezzz commented
I only have a couple small issues:
![image](https://user-images.githubusercontent.com/71992016/232171338-0db7d88b-f15a-450c-9752-d91e3a516782.png)

Red: "Cheat" should be renamed to "Cheats". 

Blue: The `Apply` button is **not** there when opening per-game settings from Citra's game list (before launching your game). It is only available *after* the game is launched through `Emulation>Configure Current Game...`
It should be available for both. 

Also, you should probably rename the `Apply` button to `Save`. Since applying a cheat code is not its function, saving it is.

Lastly, I don't like the `Apply` button's current position, nor the fact that it is visible in other settings tabs, since it has no use there. I would suggest to move it to position [1] or [2] as I've shown in the picture, so that it is specific to the `Cheats` tab (I prefer position [2]).

2023-04-14 23:57 UTC, SleepingSnakezzz commented
Other than the things I mentioned above, I couldn't find any other issues on the desktop side of things. Awesome work!

2023-04-15 00:11 UTC, luc-git commented
Another thing is that cheats are applied even without saving it in the cheat file

2023-04-15 00:14 UTC, luc-git commented
As soon as a cheat is added in https://github.com/citra-emu/citra/blob/2a2ee8bc968232058fe77a06e95d4f3fa1b851e7/src/core/cheats/cheats.h#L39 it is applied in game

2023-04-15 00:15 UTC, luc-git commented
Maybe it could be better to apply cheats only after clicking save or ok button

2023-04-16 18:01 UTC, FearlessTobi commented on src/citra_qt/configuration/configure_cheats.h
> +#include "core/cheats/cheats.h"
this seems like it can be a forward declaration

2023-04-16 21:03 UTC, luc-git commented
> Lastly, I don't like the Apply button's current position, nor the fact that it is visible in other settings tabs, since it has no use there. I would suggest to move it to position [1] or [2] as I've shown in the picture, so that it is specific to the Cheats tab (I prefer position [2]).

I don't understand why move Apply button position to delete button position?

2023-04-17 18:11 UTC, SleepingSnakezzz commented
> The apply button is not cheat specific, it has been there since per game settings were implemented. I believe it's meant as a way to adjust per game settings while the game is running, without closing the window. So imo that fix is to per-game settings in general and out of scope of this PR.
Correct. I was mixing things up (though I still don't see why this button needs to exist, but that's a different matter entirely).

@luc-git The reason why I was going on about that button is because when a user wants to enter multiple cheat codes at the same time, the `Apply` button is the only way to do so without having to constantly reopen the settings. And this button is **not** available when you open the per-game settings from the game list (before you launch your game).

For example, if I want to add 3 cheats *before* I launch a game, the only way to do so is to click `Add Cheat`, fill in the cheat code and then press `Ok`. After that, I have to reopen the per game settings again, and do that 2 more times. This is because the `Apply` button does not exist there.

It makes more sense to me to have a `Save Cheat` button next to the `Delete` or `Add Cheat` button (the positions that I marked in my screenshot) for this purpose.

2023-04-17 20:45 UTC, luc-git commented on src/citra_qt/configuration/configure_cheats.h
> +#include "core/cheats/cheats.h"
Unfortunately if I remove the cheats.h include the github workflow fails with macos and windows build. But it works for me I use visual studio IDE in windows it's weird.

2023-04-18 19:42 UTC, luc-git commented
@SleepingSnakezzz I think is good I added save button again in the cheat tab

2023-04-18 20:09 UTC, luc-git commented
Closes: #6380

2023-04-19 16:49 UTC, SleepingSnakezzz commented
Tried the PR artifact, looks good to me!

2023-04-19 16:51 UTC, luc-git commented
Ok but I don't know why forward declare CheatEngine doesn't work

2023-04-20 17:38 UTC, luc-git commented
@SleepingSnakezzz Workflow compiles successfully for windows but not for macos if I replace include by a forward declaration. I had to disable ccache to compile for windows

2023-04-21 17:03 UTC, luc-git commented
> ```
> error: unknown type name 'u64'
>     explicit ConfigureCheats(u64 title_id_, QWidget* parent = nullptr);
>                              ^
> /Users/runner/work/citra/citra/src/citra_qt/configuration/configure_cheats.h:58:5: error: unknown type name 'u64'
>     u64 title_id;
>     ^
> ```
> 
> You need to include `common/common_types.h` Edit: you might also need to `#include<vector>`

Ok thank you very much it build now. Yes it's weird it compile even if I don't include vector. But there is a std::vector declaration in the header file.

2023-04-21 17:58 UTC, FearlessTobi requested changes

2023-04-21 17:58 UTC, FearlessTobi commented on src/core/core.cpp
> +        Kernel().GetCurrentProcess()->codeset->program_id, *this);
the title id is being read already in line 317. you can just use the information from there

2023-04-21 17:58 UTC, FearlessTobi commented on src/citra_qt/configuration/configure_per_game.cpp
> +    };
```suggestion
    }
```

2023-04-21 17:58 UTC, FearlessTobi commented on src/citra_qt/configuration/configure_per_game.cpp
> +    QPushButton* buttonSender = qobject_cast<QPushButton*>(sender());
I really don't like this way of doing this.
also the variable name is not compliant with our coding style

2023-04-21 18:12 UTC, luc-git commented on src/citra_qt/configuration/configure_per_game.cpp
> +    QPushButton* buttonSender = qobject_cast<QPushButton*>(sender());
Ok but why is this variable name using the same coding style? https://github.com/citra-emu/citra/blob/f96047f18229e257297593e68cbbdf29b72b1e9b/src/citra_qt/main.cpp#L1709

2023-04-21 19:47 UTC, luc-git commented
Done but now if you press ok button cheats will only be applied if you are in the cheat tab.
This is to prevent qmessage from cheats to be opened while we are in another tab.

2023-04-25 18:47 UTC, luc-git commented
Hello changes requested are resolved anything new?

2023-04-26 13:45 UTC, FearlessTobi approved these changes

2023-04-30 14:36 UTC, merged

2023-05-29 09:12 UTC, SleepingSnakezzz commented
As this PR has said, it's now been moved to the per-game settings. Regardless, this isn't something to ask on the PR itself. Questions related to Citra should be asked on the Citra forums or in the Citra Discord server.