Fix plvpwaa dlc error
citra-emu/citra pull request #6436
Opened 2023-04-13 13:34 UTC by Rokkubro

Return 1 for the number of output entries in the GetNsDataIdList1 stub. This fixes the extra content for Professor Layton vs Phoenix Wright Ace Attorney as the game expects the boss extdata to not be empty. Might break other games if they attempt to do anything with the ns data. (although the readnsdata and deletensdata methods are both still stubbed)

2023-04-15 04:39 UTC, SachinVin commented
I don't like that this potentially breaks multiple others, in favor of fixing one game.

2023-04-15 13:25 UTC, Rokkubro commented
I’ve just pushed a commit that only makes this change if this specific game is running.

Potentially the alternative is to check for the number of files in the boss extdata directory but I think that makes too many assumptions about how the spotpass service works without actually doing a proper implementation.

2023-04-15 14:55 UTC, SachinVin commented
No game specific code in core please.

2023-04-17 03:48 UTC, PydraxAlpta commented
Can we figure out what games would break because of the first commit? I don't like a game specific exception clause but it seems that without knowing what would break and how it breaks this will be at a stalemate to not progress. What other games are known to try and access the ns data but are auto prevented by this line returning an empty boss extra data?

2023-04-17 06:26 UTC, Rokkubro commented
Ok, so now the BOSS service will attempt to check the number of files in the boss extdata directory to determine the number of output entries; if it fails or if the directory is empty it will return a 0 which should preserve the original behaviour for all other games. (and will also preserve the behaviour for PLvPWAA if the boss directory is empty.

2023-04-17 19:09 UTC, BreadFish64 requested changes

2023-04-17 19:09 UTC, BreadFish64 commented on src/core/hle/service/boss/boss.cpp
> +    rb.Push<u16>(GetOutputEntriesCount()); /// Actual number of output entries
This is dangerous since this can be larger than the buffer size and games might access out-of-bounds memory.
https://www.3dbrew.org/wiki/BOSSU:GetNsDataIdList
It doesn't seem too hard to implement properly, but this output at least needs to be the minimum of this and `max_entries`.

2023-04-18 01:05 UTC, Rokkubro commented on src/core/hle/service/boss/boss.cpp
> +    rb.Push<u16>(GetOutputEntriesCount()); /// Actual number of output entries
Ok so now there should be an array of zeroed nsdataids for the games to read in case, hopefully I used the mappedbuffer correctly here. I've done a bit of snooping with about 15 titles that use spotpass extdata and it should be relatively simple to read the actual IDs from the files each title's boss directory, and also return the payload data from each entry should a game request it. I'm not sure that's within the scope of this branch though.

2023-04-19 06:47 UTC, Rokkubro commented on src/core/hle/service/boss/boss.cpp
> +    rb.Push<u16>(GetOutputEntriesCount()); /// Actual number of output entries
Gotcha, with the new code it should only ever return a number of entries that is less than max_entries and has a readable nsdataid in the buffer. Also no longer using any VLAs, are std::vector and dynamic arrays allowed?

2023-04-19 06:54 UTC, Rokkubro commented
Made a rather large change so the service will actually read the NsDataIds from the files in the spotpass directory when GetNsDataIdList(1/2/3) is called, and will also attempt to return data from those files if ReadNsData is called.

2023-04-20 01:53 UTC, SachinVin commented
Hi, is this actually how the 3ds calculates GetNsDataIdList?

2023-04-20 09:31 UTC, Rokkubro commented
I think it’s pretty close. On the 3DS the service checks that the payload size is larger than or equal to the size in the header, here I’ve just made it equal. Also I haven’t implemented the filter parameter or distinguished between the 4 GetNsIdList functions. 

At [3dbrew](https://www.3dbrew.org/wiki/BOSSU:GetNsDataIdList) it says the filter parameter is checked against the datatype in the header and if it fails the nsdataid is not added to the list. However I haven’t been able to reproduce this at all on a real 3DS, the datatype just seems to be ignored.

2023-04-20 14:00 UTC, SachinVin commented
So, does the 3ds also iterate over the folders in `boss` and return the List ?

2023-04-22 04:55 UTC, Rokkubro commented
Yes that's right. The service actually seems to be doing some filtering of files before opening them just based on the file names. I haven't worked out exactly how that works though. 3dbrew states :"The contentdatatype is extracted from the extdata filename, which originates from the BOSS-container." so it might be that the datatype field in the header is ignored completely and it determines it from the filename somehow.

2023-04-22 21:20 UTC, FearlessTobi requested changes
Thanks for implementing this!
There are some things that need to be fixed though.

2023-04-22 21:20 UTC, FearlessTobi commented on src/core/hle/service/boss/boss.cpp
> +}
newline before and after this function

2023-04-22 21:20 UTC, FearlessTobi commented on src/core/hle/service/boss/boss.cpp
> +    FileSys::Entry boss_files[100];
can be an std::array
dito below

2023-04-22 21:20 UTC, FearlessTobi commented on src/core/hle/service/boss/boss.cpp
> +    u32 entry_count = 0;
the variable declaration can be moved down further

2023-04-22 21:20 UTC, FearlessTobi commented on src/core/hle/service/boss/boss.cpp
> +    u32 files_to_read = 100;
can be const

2023-04-22 21:20 UTC, FearlessTobi commented on src/core/hle/service/boss/boss.cpp
> +        if (boss_files[i].is_directory || boss_files[i].file_size < 52) {
replace this magic number with a meaningful variable or add a comment

2023-04-22 21:20 UTC, FearlessTobi commented on src/core/hle/service/boss/boss.cpp
> +        if (archive_result.Succeeded()) {
```suggestion
        if (!archive_result.Succeeded()) {
            LOG_WARNING(Service_BOSS, "Extdata opening failed");
            return;
        }
```
same with the other check below
it also seems like the extdata opening can happen outside the loop.

2023-04-22 21:20 UTC, FearlessTobi commented on src/core/hle/service/boss/boss.cpp
> +                if (header_length[0] != 0x18) {
magic number being used here.

2023-04-22 21:20 UTC, FearlessTobi commented on src/core/hle/service/boss/boss.cpp
> +                file->Read(0x18, 8, spotpass_program_id_array);
Consider declaring the Spotpass data as a struct and reading it in one go.
that could be a lot cleaner.

2023-04-22 21:20 UTC, FearlessTobi commented on src/core/hle/service/boss/boss.cpp
> +    if (archive_result.Succeeded()) {
consider inverting this check and returning early on errors here

2023-04-22 21:20 UTC, FearlessTobi commented on src/core/hle/service/boss/boss.cpp
> +            LOG_WARNING(Service_BOSS, "Extdata directory opened unsuccessfully :(");
```suggestion
            LOG_WARNING(Service_BOSS, "Extdata directory opening failed");
```

2023-04-22 21:20 UTC, FearlessTobi commented on src/core/hle/service/boss/boss.cpp
> +    buffer->Write(&output_entries[0], 0, sizeof(u32) * entry_count);
```suggestion
    buffer->Write(output_entries.data(), 0, sizeof(u32) * entry_count);
```

2023-04-22 21:20 UTC, FearlessTobi commented on src/core/hle/service/boss/boss.cpp
> +                    u8* ns_data_array = new u8[size];
do not use `new`.
can't this just be a vector?

2023-04-26 08:42 UTC, Rokkubro commented
@FearlessTobi I've made all the changes as you requested. Thanks for the feedback! Apologies for my poor c++ 😅

Also added in filtering by datatype as was done on the 3ds, not really used in PLvPWAA but other games do (like MK7, swapdoodle).

@PydraxAlpta A bunch of games (Mario Kart 7, Swapdoodle, Smash Bros) will infinitely hang or crash with the first commit it seems as they try to request data from the phantom entry we say exists. Mario Kart 7 attempts to do this on startup and will never reach the main menu :(

Removed the ReadNsData implementation as games will call GetNsDataHeaderInfo beforehand and I haven't finished the implementation of that.

So far I haven't worked out exactly how the filenames are encoded but I have discovered 2 important things. 
1. It contains characters representing NsDataID, payload size and datatype in that order.
2. When the BOSS service writes the data out to the extdata archive, the values recorded in the filename never differ from those stored in the header.
So it should be fine to continue to use the values from the header, even though the real 3ds gets the datatype parameter from the filename.

I think this is as far as I want to go for this pull request, I've made a new branch on my citra clone where I will work on implementing the rest of the spotpass service. For now PLvPWAA will work as long as valid spotpass data is stored in its boss extdata directory, and all other games will work as before so long as their boss extdata directory is empty.

2023-05-19 12:41 UTC, Rokkubro commented
Superseded by #6549

2023-05-19 12:41 UTC, closed without merging