Add vulkan backend
citra-emu/citra pull request #6512
Opened 2023-05-07 12:42 UTC by GPUCode

Now that all relevant changes have been upstreamed and video_core is mostly backend agnostic we can add the vulkan code. This is mostly a code dump from vulkan-2 with minimal changes.

UI changes
![εικόνα](https://user-images.githubusercontent.com/47210458/236678306-8dad3cc5-d9cd-4d6e-8055-766be060d5ba.png)

2023-05-07 13:39 UTC, FearlessTobi commented on externals/catch2
this being updated seems like a mistake?

2023-05-07 13:39 UTC, FearlessTobi commented on externals/zstd
dito

2023-05-07 13:53 UTC, FearlessTobi reviewed
Only looked at the first 54 files so far.

2023-05-07 13:53 UTC, FearlessTobi commented on src/android/app/src/main/jni/emu_window/emu_window_gl.cpp
> +        ASSERT_MSG(egl_surface, "eglCreatePbufferSurface() failed!");
why is this an assert, while in the other places you're using LOG_CRITICAL?

2023-05-07 13:53 UTC, FearlessTobi commented on src/android/app/src/main/jni/emu_window/emu_window_gl.cpp
> +    return !!egl_surface;
what does that mean?

2023-05-07 13:53 UTC, FearlessTobi commented on src/android/app/src/main/jni/emu_window/emu_window_vk.cpp
> +}
should have newline here

2023-05-07 13:53 UTC, FearlessTobi commented on src/android/app/src/main/jni/emu_window/emu_window_vk.cpp
> +void EmuWindow_Android_Vulkan::TryPresenting() {
```
void EmuWindow_Android_Vulkan::TryPresenting() {
        if (presenting_state == PresentingState::Initial) {
            presenting_state = PresentingState::Running;
        } 
}

2023-05-07 13:53 UTC, FearlessTobi commented on src/android/app/src/main/res/values/strings.xml
> +    <string name="spirv_shader_gen_description">Emits the fragment shader used to emulate PICA using SPIR-V instead of GLSL</string>
not sure if this description is helpful to the users

2023-05-07 13:53 UTC, FearlessTobi commented on src/citra_qt/bootmanager.cpp
> +bool GRenderWindow::InitializeVulkan() {
this method always returns true, can be void instead

2023-05-07 13:53 UTC, FearlessTobi commented on src/citra_qt/main.cpp
> +void GMainWindow::UpdateAPIIndicator(bool update) {
I find the way yuzu is doing this a little bit cleaner.
Maybe just copy their code here?

2023-05-07 13:53 UTC, FearlessTobi commented on src/citra_qt/main.cpp
> +    static std::array graphics_apis = {QStringLiteral("SOFTWARE"), QStringLiteral("OPENGL"),
these strings should also be translateble

2023-05-07 14:12 UTC, SachinVin commented on src/android/app/src/main/jni/emu_window/emu_window_vk.cpp
> +#include "video_core/video_core.h"
Doesnt seem like most of these headers are used

2023-05-07 16:19 UTC, BreadFish64 commented on src/android/app/src/main/jni/emu_window/emu_window_gl.cpp
> +    return !!egl_surface;
It's an idiom to cast to bool (which I am not a fan of). There's no point here since it will be coerced to bool using the same conversion by the return anyway.

2023-05-07 17:16 UTC, Steveice10 commented on src/video_core/renderer_vulkan/vk_shader_gen.cpp
> +            const std::string index = fmt::format("clamp({}.dist_atten_scale * length(-view - "
Reminder to port over the lighting distance attenuation fixes: https://github.com/citra-emu/citra/commit/506644b9d610fb0e8bfb26f8e043a770fba30bfe

For SPIR-V as well.

2023-05-07 17:38 UTC, GPUCode commented on src/video_core/renderer_vulkan/vk_shader_gen.cpp
> +            const std::string index = fmt::format("clamp({}.dist_atten_scale * length(-view - "
Already ported it over to SPIR-V, will do so for GLSL too thanks for the reminder

2023-05-08 09:31 UTC, GPUCode commented on src/citra_qt/main.cpp
> +    static std::array graphics_apis = {QStringLiteral("SOFTWARE"), QStringLiteral("OPENGL"),
Software maybe, but I don't think the terms OpenGL and Vulkan are translatable

2023-05-08 12:30 UTC, FearlessTobi commented on src/video_core/renderer_vulkan/renderer_vulkan.cpp
> +        current_pipeline = 1;
can we make these magic numbers an enum?

2023-05-08 12:35 UTC, FearlessTobi commented on src/video_core/renderer_vulkan/renderer_vulkan.h
> +static_assert(sizeof(PresentUniformData) < 256, "PresentUniformData must be below 256 bytes!");
can we make this size check exact? 
it doesn't seem like the size of the struct can change randomly

2023-05-08 12:37 UTC, FearlessTobi commented on src/video_core/renderer_vulkan/vk_common.h
> +#include "common/common_types.h"
are these two includes needed here?

2023-05-08 12:39 UTC, FearlessTobi commented on src/video_core/renderer_vulkan/vk_descriptor_manager.cpp
> +#include "vulkan/vulkan.hpp"
externals are usually included with <> braces

2023-05-08 12:40 UTC, FearlessTobi commented on src/video_core/renderer_vulkan/vk_descriptor_manager.h
> +    [[nodiscard]] bool operator!=(const DescriptorData& other) const noexcept {
should also have the `operator==` defined for completeness

2023-05-08 13:30 UTC, JohelEGP commented on src/video_core/renderer_vulkan/vk_descriptor_manager.h
> +    [[nodiscard]] bool operator!=(const DescriptorData& other) const noexcept {
In C++20 (used since #6115), actually only `operator==` is necessary. `!=` will be a rewritten candidate.

2023-05-08 13:46 UTC, SachinVin commented on .gitmodules
> +    url = https://github.com/GPUCode/sirit
Any reason not to use yuzu's?

2023-05-08 14:13 UTC, SachinVin commented on src/video_core/renderer_vulkan/pica_to_vk.h
> +    if (index >= logic_op_table.size()) {
ASSERT?

2023-05-08 14:30 UTC, SachinVin commented on src/video_core/renderer_vulkan/vk_pipeline_cache.h
> +namespace Common {
Why is common here?

2023-05-08 17:05 UTC, GPUCode commented on .gitmodules
> +    url = https://github.com/GPUCode/sirit
My fork contains some additional spirv operations required for the fragment shader emitter

2023-05-08 17:05 UTC, GPUCode commented on src/android/app/src/main/jniLibs/arm64-v8a/libVkLayer_khronos_timeline_semaphore.so
This is the timeline semaphore emulation layer, which is required on older mali/adreno devices that don't have the extension

2023-05-08 17:06 UTC, GPUCode commented on src/android/app/src/main/jniLibs/arm64-v8a/libVkLayer_khronos_validation.so
These is the validation layer binary which is used with debug renderer

2023-05-08 17:08 UTC, GPUCode commented on src/android/app/src/main/res/values/strings.xml
> +    <string name="spirv_shader_gen_description">Emits the fragment shader used to emulate PICA using SPIR-V instead of GLSL</string>
I can't really think of any other way to describe the setting, any suggestions?

2023-05-08 17:13 UTC, GPUCode commented on src/video_core/rasterizer_cache/rasterizer_cache.h
> +    Surface* const color_surface = color_id ? &slot_surfaces[color_id] : nullptr;
The framebuffer class calls FramebufferView which modifies a flag in the surface object

2023-05-08 17:13 UTC, GPUCode commented on src/video_core/renderer_base.h
> -    virtual VideoCore::RasterizerInterface* Rasterizer() const = 0;
It wasn't, I just removed the const attribute

2023-05-08 17:16 UTC, GPUCode commented on src/video_core/renderer_vulkan/pica_to_vk.h
> +    if (index >= logic_op_table.size()) {
All other functions don't use ASSERT either, what's special about the logic op one?

2023-05-08 17:17 UTC, GPUCode commented on src/video_core/renderer_vulkan/vk_instance.h
> +        // Geometry shaders are extremely expensive on tilers to avoid them at all
I haven't  benchmarked it either but geometry shaders seem broken in many devices. Tried enabling them in the past which resulted in graphical glitches to most games

2023-05-08 17:18 UTC, GPUCode commented on src/video_core/renderer_vulkan/vk_platform.cpp
> +std::vector<const char*> GetInstanceExtensions(Frontend::WindowSystemType window_type,
The extension list is passed to ppEnabledExtensionNames which is const char** so using std::string here might break things

2023-05-08 17:21 UTC, GPUCode commented on src/video_core/renderer_vulkan/renderer_vulkan.cpp
> +    for (u32 i = 0; i < 3; i++) {
This is ported directly from the opengl code. The first two render targets are for the top screen (one of the left and one for the right eye) while the third one is for the bottom screen.

2023-05-08 17:30 UTC, GPUCode commented on src/video_core/host_shaders/format_reinterpreter/d24s8_to_rgba8.frag
> -layout(location = 0) in mediump vec2 tex_coord;
glslang doesn't like precision statements for some reason

2023-05-09 06:11 UTC, SachinVin commented on .gitmodules
> +    url = https://github.com/GPUCode/sirit
Can you upstream them?

2023-05-09 06:12 UTC, SachinVin commented on src/android/app/src/main/jniLibs/arm64-v8a/libVkLayer_khronos_timeline_semaphore.so
Is there a better way to do this? Adding binarys to the repo is not preferred

2023-05-09 06:13 UTC, SachinVin commented on src/video_core/renderer_vulkan/vk_platform.cpp
> +std::vector<const char*> GetInstanceExtensions(Frontend::WindowSystemType window_type,
Okay

2023-05-09 07:31 UTC, GPUCode commented on src/video_core/renderer_vulkan/pica_to_vk.h
> +namespace PicaToVK {
In OpenGL the functions are still in the PicaToGL namespace, don't see how it's different here

2023-05-09 13:54 UTC, SachinVin commented on src/video_core/renderer_vulkan/pica_to_vk.h
> +    if (index >= logic_op_table.size()) {
Ditto for the other functions too 😅

> what's special about the logic op one?

Nothing other than me being blind

2023-05-09 14:07 UTC, GPUCode commented on src/video_core/renderer_vulkan/pica_to_vk.h
> +    if (index >= logic_op_table.size()) {
Alright, do you want me to change the OpenGL functions too while at it?

2023-05-09 14:29 UTC, GPUCode commented on src/android/app/src/main/jniLibs/arm64-v8a/libVkLayer_khronos_timeline_semaphore.so
I think the extension layer repo can be configured to build as a submodule. Though I'm exploring writing a fence fallback instead of relying on it

2023-05-09 14:30 UTC, GPUCode commented on src/video_core/renderer_vulkan/vk_pipeline_cache.h
> +namespace Common {
This is from the async_handle.h header but I remember Breadfish recommending to use std::binary_semaphore so this is kinda of a hotfix to avoid adding that header to common again

2023-05-09 15:42 UTC, FearlessTobi reviewed
100/112

2023-05-09 15:42 UTC, FearlessTobi commented on src/video_core/renderer_vulkan/vk_instance.cpp
> +    const auto IsSupported = [&extensions](std::string_view requested) {
```suggestion
    const auto is_supported = [&extensions](std::string_view requested) {
```

2023-05-09 15:42 UTC, FearlessTobi commented on src/video_core/renderer_vulkan/vk_instance.cpp
> +        for (u32 count = 1; count <= 4; count++) {
`count` is not very descriptive, especially when used with magic numbers

2023-05-09 15:42 UTC, FearlessTobi commented on src/video_core/renderer_vulkan/vk_instance.cpp
> +    const auto AddExtension = [&](std::string_view extension, bool blacklist = false,
```suggestion
    const auto add_extension = [&](std::string_view extension, bool blacklist = false,
```

2023-05-09 15:42 UTC, FearlessTobi commented on src/video_core/renderer_vulkan/vk_instance.cpp
> +        auto result = std::find_if(available_extensions.begin(), available_extensions.end(),
```suggestion
       const auto result = std::find_if(available_extensions.begin(), available_extensions.end(),
```

2023-05-09 15:42 UTC, FearlessTobi commented on src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
> +    const auto AppendHash = [&info_hash](const auto& data) {
```suggestion
    const auto append_hash = [&info_hash](const auto& data) {
```

2023-05-09 15:42 UTC, FearlessTobi commented on src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
> +        LOG_INFO(Render_Vulkan, "Unable to open pipeline cache for writing");
```suggestion
        LOG_ERROR(Render_Vulkan, "Unable to open pipeline cache for writing");
```

2023-05-09 15:42 UTC, FearlessTobi commented on src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
> +        LOG_WARNING(Render_Vulkan, "Error during pipeline cache write");
```suggestion
        LOG_ERROR(Render_Vulkan, "Error during pipeline cache write");
```

2023-05-09 15:42 UTC, FearlessTobi commented on src/video_core/renderer_vulkan/vk_pipeline_cache.cpp
> +    const auto CreateDir = [](const std::string& dir) {
```suggestion
    const auto create_dir = [](const std::string& dir) {
```

2023-05-09 15:42 UTC, FearlessTobi commented on src/video_core/renderer_vulkan/vk_present_window.cpp
> +        // Retry if the waiting time out
```suggestion
        // Retry if the waiting times out
```
??

2023-05-09 15:42 UTC, FearlessTobi commented on src/video_core/renderer_vulkan/vk_rasterizer.cpp
> +    for (u32 i = 0; i < 7; i++) {
where does this number come from?

2023-05-09 15:42 UTC, FearlessTobi commented on src/video_core/renderer_vulkan/vk_rasterizer.cpp
> +    auto SyncProcTexValueLUT =
```suggestion
    auto sync_proctex_value_lut =
```

2023-05-09 15:42 UTC, FearlessTobi commented on src/video_core/renderer_vulkan/vk_renderpass_cache.h
> +    vk::RenderPass cached_renderpasses[MAX_COLOR_FORMATS + 1][MAX_DEPTH_FORMATS + 1][2];
does this need to hold an extra render_pass or is this a mistake?

2023-05-09 16:44 UTC, GPUCode commented on src/video_core/renderer_vulkan/vk_renderpass_cache.h
> +    vk::RenderPass cached_renderpasses[MAX_COLOR_FORMATS + 1][MAX_DEPTH_FORMATS + 1][2];
Yes the first index is reversed for the undefined format

2023-05-09 19:58 UTC, GPUCode commented on src/video_core/renderer_vulkan/vk_rasterizer.cpp
> +    for (u32 i = 0; i < 7; i++) {
The shader has 7 storage images it can access for shadow rendering

2023-05-09 20:03 UTC, GPUCode commented on src/video_core/renderer_vulkan/renderer_vulkan.cpp
> +        current_pipeline = 1;
I don't see how an enum would help here. The current code I believe is descriptive enough on which pipeline is used when. Adding an additional enum would just be more static_casts imo

2023-05-10 07:20 UTC, SachinVin commented on CMakeModules/BundleLibraries.cmake
> +            message(WARNING "Skipping Vulkan SDK bundling since no SDK path was provided.")
IMO this should be fatal

2023-05-10 09:40 UTC, SachinVin commented on src/android/app/src/main/jni/default_ini.h
> +# Whether to emit PICA fragment shader using SPIRV or GLSL
Should probably clarify that this only when vulkan is used

2023-05-10 09:40 UTC, SachinVin commented on src/android/app/src/main/jni/default_ini.h
> +async_shader_compilation
```suggestion
async_shader_compilation =
```

2023-05-10 09:41 UTC, SachinVin commented on src/android/app/src/main/jni/default_ini.h
> +# 1: SPIR-V (default), 0: GLSL
```suggestion
# 0: GLSL, 1: SPIR-V (default)
```

2023-05-10 09:48 UTC, SachinVin commented on src/android/app/src/main/jni/emu_window/emu_window_gl.cpp
> +    }
```suggestion
      if [[unlikely]] (presenting_state == PresentingState::Initial) {
          eglMakeCurrent(egl_display, egl_surface, egl_surface, egl_context);
          glBindFramebuffer(GL_DRAW_FRAMEBUFFER, 0);
          presenting_state = PresentingState::Running;
      } 
      if [[unlikely]] (presenting_state != PresentingState::Running) {
          return;
      }
```

2023-05-10 09:55 UTC, SachinVin commented on src/citra/emu_window/emu_window_sdl2_vk.h
> +#include "core/frontend/emu_window.h"
is this for `Frontend::GraphicsContext`? it can probably be forward declared.

2023-05-10 10:19 UTC, SachinVin commented on src/video_core/host_shaders/format_reinterpreter/vulkan_d24s8_to_rgba8.comp
> +#version 450 core
430?

2023-05-10 10:20 UTC, SachinVin commented on src/video_core/renderer_base.h
> -    virtual VideoCore::RasterizerInterface* Rasterizer() const = 0;
why was the cont attribute removed ?

2023-05-10 10:25 UTC, GPUCode commented on src/video_core/host_shaders/format_reinterpreter/vulkan_d24s8_to_rgba8.comp
> +#version 450 core
Vulkan GLSL version doesn't really matter, since it's translated to SPIR-V 1.3 in the end

2023-05-10 10:25 UTC, SachinVin commented on src/video_core/renderer_vulkan/renderer_vulkan.cpp
> +             0.f,         0.f,          0.f, 1.f};
```suggestion
             0.f,         0.f,          0.f,  1.f};
```

2023-05-10 10:27 UTC, SachinVin commented on src/video_core/renderer_vulkan/renderer_vulkan.cpp
> +std::string GetReadableVersion(u32 version) {
shouldnt this bee in vk_driver or something similar?

2023-05-10 10:36 UTC, SachinVin commented on src/video_core/renderer_vulkan/renderer_vulkan.cpp
> +            LOG_CRITICAL(Render_Vulkan, "Unable to build present pipelines");
can probably be simplified with `ASSERT_MSG(result.result == vk::Result::eSuccess, "Unable to build present pipelines")`

2023-05-10 10:37 UTC, SachinVin commented on src/video_core/renderer_vulkan/renderer_vulkan.cpp
> +    if (result != VK_SUCCESS) [[unlikely]] {
can simply be ASSERT _MSG

2023-05-10 10:45 UTC, SachinVin commented on src/video_core/renderer_vulkan/vk_blit_helper.cpp
> +        LOG_CRITICAL(Render_Vulkan, "Compute pipeline creation failed!");
can be ASSERT_MSG

2023-05-10 10:51 UTC, SachinVin commented on src/video_core/renderer_vulkan/vk_renderpass_cache.cpp
> +    if (cmd_count > 20 && instance.ShouldFlush()) {
why specifically 20 ?

2023-05-10 10:55 UTC, SachinVin commented on src/video_core/renderer_vulkan/vk_rasterizer.cpp
> +    for (u32 i = 0; i < 7; i++) {
in pica ?

2023-05-10 11:01 UTC, SachinVin commented on src/video_core/renderer_vulkan/vk_rasterizer.cpp
> +                if (u32 size = vertex_attributes.GetNumElements(attribute_index); size != 0) {
```suggestion
            if (attribute_index > 11) {
                ...
                continue;
            }
            u32 size = vertex_attributes.GetNumElements(attribute_index);
            if (!size) {
                continue;
            }
```

2023-05-10 11:05 UTC, SachinVin commented on src/video_core/renderer_vulkan/vk_rasterizer.cpp
> +    if (regs.pipeline.use_gs != Pica::PipelineRegs::UseGS::No) {
wouldn't this just fallback to the jit most of the time ?

2023-05-10 11:24 UTC, SachinVin commented on src/video_core/renderer_vulkan/vk_scheduler.cpp
> +            const std::array signal_values{signal_value, u64(0)};
```suggestion
            const std::array signal_values{signal_value, 0ul};
```

2023-05-10 11:28 UTC, SachinVin commented on src/video_core/renderer_vulkan/vk_shader_gen.cpp
seems like a lot of duplicate code, can't this be common for gl and vk ?

2023-05-10 11:34 UTC, GPUCode commented on src/video_core/renderer_vulkan/vk_rasterizer.cpp
> +    for (u32 i = 0; i < 7; i++) {
Pica can use either 1 or 6 shadow planes. The extra here is the shadow_buffer which is normally the color attachment but it's attached as a storage image because it's written with imageStoreAtomicCompSwap

2023-05-10 14:17 UTC, FearlessTobi reviewed
110/112

2023-05-10 14:17 UTC, FearlessTobi commented on src/video_core/renderer_vulkan/vk_shader_gen_spv.cpp
> +    : Sirit::Module{0x00010300}, config{config} {
what is this value?

2023-05-10 14:17 UTC, FearlessTobi commented on src/video_core/renderer_vulkan/vk_shader_gen_spv.cpp
> +    const auto Perturbation = [&]() -> Id {
```suggestion
    const auto perturbation = [&]() -> Id {
```

2023-05-10 14:17 UTC, FearlessTobi commented on src/video_core/renderer_vulkan/vk_shader_gen_spv.cpp
> +    const auto GetLutValue = [&](LightingRegs::LightingSampler sampler, u32 light_num,
dito. i won't comment on further occurences, just check for yourself :)

2023-05-10 14:17 UTC, FearlessTobi commented on src/video_core/renderer_vulkan/vk_shader_util.cpp
> +    int default_version = 450;
```suggestion
   const int default_version = 450;
```

2023-05-10 14:17 UTC, FearlessTobi commented on src/video_core/renderer_vulkan/vk_shader_util.cpp
> +        fmt::print("{}", code);
`LOG_INFO`?

2023-05-10 14:17 UTC, FearlessTobi commented on src/video_core/renderer_vulkan/vk_shader_util.cpp
> +        LOG_CRITICAL(Render_Vulkan, "Shader Info Log:\n{}\n{}", shader->getInfoLog(),
can we make this error message a bit more descriptive? "Info log" right now doesn't sound like an error to me, even though it gets printed when the shaders fails to parse?
Dito below

2023-05-10 14:17 UTC, FearlessTobi commented on src/video_core/renderer_vulkan/vk_shader_util.cpp
> +    if (level == ShaderOptimization::Debug) {
`[[unlikely]]`?

2023-05-10 14:17 UTC, FearlessTobi commented on src/video_core/renderer_vulkan/vk_shader_util.cpp
> +    if (!shader->parse(&DefaultTBuiltInResource, default_version, profile, false, true, messages,
`[[unlikely]]`?

2023-05-10 14:17 UTC, FearlessTobi commented on src/video_core/renderer_vulkan/vk_shader_util.h
> +enum class ShaderOptimization { High = 0, Debug = 1 };
```suggestion
enum class ShaderOptimization { Normal = 0, Debug = 1 };
```

2023-05-10 14:17 UTC, FearlessTobi commented on src/video_core/renderer_vulkan/vk_stream_buffer.h
> +        return 0;
is this intended?

2023-05-10 20:59 UTC, GPUCode commented on src/video_core/renderer_vulkan/vk_shader_gen_spv.cpp
> +    : Sirit::Module{0x00010300}, config{config} {
It's the SPIR-V version sirit will generate. We target vulkan 1.1 which defines up to SPIR-V 1.3

2023-05-10 20:59 UTC, GPUCode commented on src/video_core/renderer_vulkan/vk_shader_gen.h
> +        } light[8];
Yes it's an array of anonymous structs

2023-05-10 21:00 UTC, GPUCode commented on src/video_core/renderer_vulkan/vk_shader_gen.cpp
I agree, but could it be in another PR? I plan on commonizing and rewriting the shader decompiler in the near future anyway

2023-05-10 21:00 UTC, GPUCode commented on src/video_core/renderer_vulkan/vk_renderpass_cache.cpp
> +    if (cmd_count > 20 && instance.ShouldFlush()) {
Hand picked heuristic based on testing

2023-05-10 21:01 UTC, GPUCode commented on src/video_core/renderer_vulkan/renderer_vulkan.cpp
> +std::string GetReadableVersion(u32 version) {
Imo this is a pretty specific function for logging that could also belong here. In vk_instance I prefer to put more general query functions that could be used elsewere in the backend

2023-05-10 21:10 UTC, GPUCode commented on src/android/app/src/main/jni/emu_window/emu_window.cpp
> +    Network::Init();
Network is initialized in all emu_window implementations, so it didn't seem strange to me. Should I keep it the call?

2023-05-10 21:12 UTC, GPUCode commented on src/android/app/src/main/jni/default_ini.h
> +# 0: Off, 1: On (default)
Android has really bad stutters with the current shader generator, this helps make gameplay smoother. Though it still needs some tweaks

2023-05-10 21:23 UTC, GPUCode commented on src/video_core/renderer_vulkan/vk_stream_buffer.h
> +        return 0;
Oops, no that's not

2023-05-10 21:29 UTC, GPUCode commented on src/video_core/renderer_vulkan/vk_instance.cpp
> +        for (u32 count = 1; count <= 4; count++) {
count refers to the component count (1, 2, 3, 4) of the vertex format.

2023-05-10 21:30 UTC, GPUCode commented on src/android/app/src/main/jniLibs/arm64-v8a/libVkLayer_khronos_timeline_semaphore.so
Pushed a commit with the fence fallback this is no longer needed

2023-05-10 21:34 UTC, GPUCode commented on .gitmodules
> +    url = https://github.com/GPUCode/sirit
Switched to yuzu upstrea

2023-05-10 21:40 UTC, GPUCode commented on src/video_core/renderer_base.h
> -    virtual VideoCore::RasterizerInterface* Rasterizer() const = 0;
Because vulkan keeps the rasterizer as a plain member instead of a unique_ptr. There's not much point in the rasterizer being a unique_ptr anyway

2023-05-10 21:41 UTC, GPUCode commented on src/video_core/renderer_vulkan/renderer_vulkan.cpp
> +    for (u32 i = 0; i < 3; i++) {
Closing this, as refactoring this code is a significant undertaking (I've tried) and not too worth it

2023-05-11 19:36 UTC, FearlessTobi reviewed
112/112

2023-05-11 19:36 UTC, FearlessTobi commented on src/video_core/renderer_vulkan/vk_texture_runtime.cpp
> +        const std::array<Image, 3>& images = alloc.images;
```suggestion
        const auto& images = alloc.images;
```

2023-05-11 22:13 UTC, kongfl888 commented on src/citra_qt/configuration/configure_graphics.cpp
> +    const auto physical_devices = instance.GetPhysicalDevices();
There may be a situation that needs to be considered?
If the user's device does not support vk.

2023-05-12 13:47 UTC, 9tin9tin9 commented
Just wanted to say thank you for all these work making vulkan backend possible. I have tried using the Mac x86 build playing MH4G on 2017 Macbook Pro. I only observe minor graphical glitches (Map texture sometimes gone and screenshot background at clear screen is gone) and very steady 30fps (Async shader compilation on and async presentation off). Imagine I have been using `citra-osx-20220801-bf6e4a4` build for a long time to play MH3G/MH4G. This is really a great step forward.

Not sure if I should report bugs here or where / dev team is already aware about these but
- Audio is dead. Switching to a new audio device plays audio for a few seconds and suddenly audio is gone.
- Pressing Cmd-, (the default shortcut to open Preference menu) in game crashes citra immediately

I can give you my logs and Apple crash report if the dev team is interested in investigating the bugs.

2023-05-12 15:58 UTC, Dragios commented
All games still crashes with Debug Renderer OFF at least on AMD Hardware.

2023-05-12 16:08 UTC, GPUCode commented
> All games still crashes with Debug Renderer OFF at least on AMD Hardware.

The CI uses MinGW 12.2.0 which has a bug that manifests only on AMD. Use msvc builds in this case

2023-05-12 19:38 UTC, GPUCode commented
@9tin9tin9 I think it would be best if you went over to our discord for support regarding your issue

2023-05-13 00:29 UTC, Steveice10 commented
Untagging until AppImage is sorted out so other PRs can land in Canary.

2023-05-13 02:58 UTC, 9tin9tin9 commented
one more think to mention about the vulkan build is that I left citra paused in game at the background whole night and the cpu/gpu is very hot despite it not using any cpu/gpu as seen from Activity Monitor. I guess it's caused by turning on both Async graphics features?

2023-05-16 14:12 UTC, Dragios commented
Pokémon X/Y is partially broken in OpenGL mode. But if the internal resolution is changed (such as maximizing window) then it will fixed itself. This workaround will only work with Auto (window size). If set as native or any other internal resolution initially this workaround won't work at all.
![image](https://github.com/citra-emu/citra/assets/18496868/0b9a626e-4f83-4c8e-93cf-5da80938b673)

2023-05-16 14:45 UTC, GPUCode commented
Is it broken in this PR specifically, or in Nightly too?

2023-05-16 16:27 UTC, Dragios commented
> Is it broken in this PR specifically, or in Nightly too?
This PR, nightly is fine.

2023-05-16 19:43 UTC, vitor-k commented on src/video_core/host_shaders/CMakeLists.txt
> -    format_reinterpreter/fullscreen_quad.vert
Are these removals intentional? The files weren't changed

2023-05-16 19:48 UTC, GPUCode commented on src/video_core/host_shaders/CMakeLists.txt
> -    format_reinterpreter/fullscreen_quad.vert
Yes every render to texture effect in opengl uses full_screen_triangle.vert now. Vulkan only uses compute shaders for now

2023-05-16 19:48 UTC, GPUCode commented on src/citra_qt/configuration/configure_graphics.cpp
> +    const auto physical_devices = instance.GetPhysicalDevices();
Added code to prevent crash when vulkan is unsupported

2023-05-18 08:58 UTC, benderscruffy commented
Ridge Racer 3D
using vulkan backend the emulator crashes out now at the start of the race

2023-05-18 19:29 UTC, GPUCode commented on src/video_core/host_shaders/format_reinterpreter/d24s8_to_rgba8.frag
> -layout(location = 0) in mediump vec2 tex_coord;
Fixed

2023-05-18 20:11 UTC, stuken commented
There's an OpenGL regression with Xenoblade. Screenshots show at x2 but it's the same at native. A screen swap or changing rendering res fixes it temporarily.
Nightly 1907
![Xenoblade Chronicles 3D_18 05 23_20 58 42 276](https://github.com/citra-emu/citra/assets/8155719/668d0752-9d0f-4c96-bb6b-985e76af1384)
Canary 2491
![Xenoblade Chronicles 3D_18 05 23_20 59 23 296](https://github.com/citra-emu/citra/assets/8155719/4af98d3a-ffe0-4c4a-876b-ac672f3902d8)

Ridge Racer 3D also shows weirdly culled faces on the cars and course selection models on the selection screens.

2023-05-18 21:40 UTC, windwakr commented
When using Vulkan with vsync enabled I'm not able to adjust the game speed beyond 100%. This problem doesn't occur with OpenlGL.

2023-05-23 07:32 UTC, PabloMK7 commented on src/android/app/src/main/res/values/strings.xml
> +    <string name="spirv_shader_gen_description">Emits the fragment shader used to emulate PICA using SPIR-V instead of GLSL</string>
May be worth explaining why it is worth enabling or disabling it (does it improve performance? does it fix bugs in some games?, etc)

2023-05-29 05:42 UTC, fantesykikachu commented on src/video_core/renderer_opengl/gl_texture_runtime.cpp
> +void TextureRuntime::TickFrame() {
Can you explain the need for this; was the queue overfilling, cause this just seems like a source of endless bugs.

2023-05-30 11:45 UTC, stuken commented on src/video_core/renderer_opengl/gl_texture_runtime.cpp
> +constexpr u64 TICKS_TO_DESTROY = 10;
TICKS_TO_DESTROY appears to be too low. It's the cause of the missing graphics I've found in Xenoblade, Ridge Racer, SMT IV, Cave Story and Puzzle Bobble Universe. Bumping this to 256 has fixed the issues in all the above titles.

2023-05-31 07:49 UTC, GPUCode commented on src/video_core/renderer_opengl/gl_texture_runtime.cpp
> +void TextureRuntime::TickFrame() {
This is a queue for destroying unused allocations. Previously they were cached forever and would cause slowdowns

2023-05-31 07:50 UTC, GPUCode commented on src/video_core/renderer_opengl/gl_texture_runtime.cpp
> +constexpr u64 TICKS_TO_DESTROY = 10;
OpenGL shouldn't care about the ticks to destroy, this only exists to give a chance to the game to recycle frequently used allocations. I suspect there's another issue at play. The whole allocation caching needs a redesign anyway

2023-06-01 21:06 UTC, fantesykikachu commented on src/video_core/renderer_opengl/gl_texture_runtime.cpp
> +constexpr u64 TICKS_TO_DESTROY = 10;
Maybe you should remove it from this PR, as it is suppose to be adding the vulkan backend, then add it in a follow up PR; although since it is just a speed up I would probably just wait until the redesign.

2023-06-03 14:03 UTC, DonelBueno commented
This PR introduced some issues for me:

- Mario Kart 7 crashes on Vulkan
- Pokemon Omega Ruby has a severe screen flash issue in-game on OpenGL
- Some custom textures doesn't load on Vulkan in Pokemon Omega Ruby (they load just fine on OpenGL), maybe other games are affected as well

2023-06-05 14:30 UTC, Steveice10 commented
Please rebase on top of merged Vulkan prep-work from other PR, and if you could do remove the dynarmic update so it can be replaced by https://github.com/citra-emu/citra/pull/6596

2023-06-05 14:54 UTC, GPUCode commented
Rebased

2023-06-06 22:57 UTC, RocketRobz commented
Taking a screenshot seems to cause Citra to crash with Vulkan enabled.

Using an NVIDIA GeForce RTX 3060 card.

2023-06-13 18:32 UTC, okt04175 commented
`nvidia implemented Vulkan 1.2 supported without support for VK_EXT_robustness2 in tegra X1/X2`
https://github.com/yuzu-emu/yuzu/pull/10635

2023-06-13 18:51 UTC, GPUCode commented
> `nvidia implemented Vulkan 1.2 supported without support for VK_EXT_robustness2 in tegra X1/X2` [yuzu-emu/yuzu#10635](https://github.com/yuzu-emu/yuzu/pull/10635)

Citra doesn't even use this extension and only requires 1.1

2023-06-13 18:55 UTC, FearlessTobi requested changes

2023-06-13 18:55 UTC, FearlessTobi commented on .gitmodules
> +	url = https://github.com/bylaws/libadrenotools
Should have a newline here

2023-06-13 18:55 UTC, FearlessTobi commented on .gitmodules
> +[submodule "externals/libadrenotools"]
```suggestion
[submodule "libadrenotools"]
```

2023-06-13 18:55 UTC, FearlessTobi commented on externals/CMakeLists.txt
> +endif()
newline

2023-06-13 18:55 UTC, FearlessTobi commented on .github/workflows/ci.yml
> +      - name: Upload
should probably be commented out again for now

2023-06-13 18:55 UTC, FearlessTobi commented on src/android/app/src/main/java/org/citra/citra_emu/features/settings/ui/SettingsActivity.java
This entire file needs to be reformatted.

2023-06-13 18:55 UTC, FearlessTobi commented on src/android/app/src/main/java/org/citra/citra_emu/utils/GpuDriverHelper.java
This file needs to be reformatted

2023-06-13 18:55 UTC, FearlessTobi commented on src/android/app/src/main/java/org/citra/citra_emu/utils/GpuDriverHelper.java
> +// SPDX-License-Identifier: GPL-2.0-or-later
Wrong license header

2023-06-13 18:55 UTC, FearlessTobi commented on src/android/app/src/main/java/org/citra/citra_emu/utils/GpuDriverHelper.java
> +    private static String customDriverLibraryName() {
```suggestion
    private static String getCustomDriverLibraryName() {
```

2023-06-13 18:55 UTC, FearlessTobi commented on src/android/app/src/main/java/org/citra/citra_emu/utils/GpuDriverMetadata.java
> +}
needs a newline

2023-06-13 18:55 UTC, FearlessTobi commented on src/android/app/src/main/java/org/citra/citra_emu/utils/GpuDriverMetadata.java
> +// SPDX-License-Identifier: GPL-2.0-or-later
wrong license header

2023-06-13 18:55 UTC, FearlessTobi commented on src/android/app/src/main/java/org/citra/citra_emu/utils/GpuDriverMetadata.java
> +            JSONObject json = new JSONObject(jsonStr);
```suggestion
            JSONObject json = new JSONObject(getStringFromFile(metadataFilePath));
```

2023-06-13 18:55 UTC, FearlessTobi commented on src/android/app/src/main/jni/camera/ndk_camera.cpp
> -        void operator()(type* ptr) {                                                               \
not related to the vulkan backend, please remove

2023-06-13 18:55 UTC, FearlessTobi commented on src/android/app/src/main/jni/native.cpp
> +    int featureFlags{};
```suggestion
    int feature_flags{};
```

2023-06-13 18:55 UTC, FearlessTobi commented on src/android/app/src/main/jni/native.cpp
> +        LOG_INFO(Frontend, "Intall custom gpu driver {}", custom_driver_name.c_str());
```suggestion
        LOG_INFO(Frontend, "Intalling custom GPU driver {}", custom_driver_name.c_str());
```

2023-06-13 18:55 UTC, FearlessTobi commented on src/android/app/src/main/jni/native.cpp
> +        LOG_INFO(Frontend, "Using system defualt gpu driver");
```suggestion
        LOG_INFO(Frontend, "Using system default GPU driver");
```

2023-06-13 18:55 UTC, FearlessTobi commented on src/android/app/src/main/jni/native.cpp
> +    // Try to load the system driver.
```suggestion
    // Try to load the system driver
```

2023-06-13 18:55 UTC, FearlessTobi commented on src/video_core/rasterizer_cache/rasterizer_cache.h
> +    runtime.TickFrame();
this seems unrelated to the vulkan backend, please seperate these changes out

2023-06-13 18:55 UTC, FearlessTobi commented on src/video_core/renderer_opengl/gl_texture_runtime.cpp
> +constexpr u64 TICKS_TO_DESTROY = 10;
Unrelated to Vulkan, please remove

2023-06-15 23:29 UTC, Steveice10 commented on src/common/CMakeLists.txt
> +    dynamic_library.h
I'm not exactly sure what this was introduced for over the Vulkan DynamicLoader, but since this canary has been in conflict between this PR and #6570

2023-06-16 06:34 UTC, GPUCode commented on src/common/CMakeLists.txt
> +    dynamic_library.h
It's remnant from the custom drivers PR, I'll remove it

2023-06-17 19:33 UTC, GPUCode commented
Temporarily untagging until https://github.com/citra-emu/citra/pull/6620 is merged

2023-06-20 12:48 UTC, Adamillo commented
Aw crap this PR has conflicts now :(

2023-06-21 18:30 UTC, Steveice10 commented on .github/workflows/ci.yml
> +      - name: Upload
This needs to be kept commented to not conflict with the CI PR, I can enable macOS builds there.

2023-06-28 22:45 UTC, GPUCode commented
Rebased

2023-08-03 10:43 UTC, benderscruffy commented
Ridge Racer 3D crashes out at the start of a race with vulcan

[  53.646577] Render.Vulkan <Critical> video_core/renderer_vulkan/vk_present_window.cpp:CopyToSwapchain:469: Device lost during present submit: vk::Queue::submit: ErrorDeviceLost
[  53.646583] Debug <Critical> video_core/renderer_vulkan/vk_present_window.cpp:operator():470: Unreachable code!

2023-08-03 11:36 UTC, GPUCode commented
> Ridge Racer 3D crashes out at the start of a race with vulcan
> 
> [ 53.646577] Render.Vulkan video_core/renderer_vulkan/vk_present_window.cpp:CopyToSwapchain:469: Device lost during present submit: vk::Queue::submit: ErrorDeviceLost [ 53.646583] Debug video_core/renderer_vulkan/vk_present_window.cpp:operator():470: Unreachable code!

Cannot reproduce the crash. Does it occur in a specific race?

2023-08-04 01:12 UTC, benderscruffy commented
doesnt matter now
just started a new game and now it goes ingame

2023-08-04 03:03 UTC, 9tin9tin9 commented
Why is there canary build for Mac but no artifacts for mac here?

MH4G crashed on Canary 2575 when simply walking in street
```
[  46.973525] Render.Vulkan <Critical> video_core/renderer_vulkan/vk_swapchain.cpp:AcquireNextImage:96: Swapchain acquire returned unknown result -4
> core/hle/service/apt/apt.cpp:AppletUtility:698: (STUBBED) called command=0X00000004, input_size=0X00000001, output_size=0X00000001
[  46.973525] Render.Vulkan <Critical> video_core/renderer_vulkan/vk_swapchain.cpp:AcquireNextImage:96: Swapchain acquire returned unknown result -4
```
Sometimes its the EmuThread crashing, sometimes its the vulkan present thread crashing.

2023-08-07 23:16 UTC, DonelBueno commented
> On canary 2578, it crashes immediately when I try to launch a game. No problems with OpenGL. Here's the [log.txt file](https://pastebin.com/TznT1kD8) My gpu is r7 250, BTW.

Have you tried disabling Custom Textures?

2023-08-13 01:37 UTC, Dragios commented
WWE All Stars Graphical Glitch
https://github.com/citra-emu/citra/assets/18496868/5d9dfd59-4c06-4528-b11a-e88b02d035eb
I have tried to _Enable Debug Renderer_ but it did not display any log when it happens

Apologies for poor video quality, have to record externally (cannot reproduce issue when screen record)
https://github.com/citra-emu/citra/assets/18496868/8a30289a-4356-4f3c-b3e3-aa3f7f5f4a7a
Texture flickering only occurs when enable _Async Presentation_

2023-08-13 14:56 UTC, GPUCode commented
> WWE All Stars Graphical Glitch https://github.com/citra-emu/citra/assets/18496868/5d9dfd59-4c06-4528-b11a-e88b02d035eb I have tried to _Enable Debug Renderer_ but it did not display any log when it happens
> 
> Apologies for poor video quality, have to record externally (cannot reproduce issue when screen record) https://github.com/citra-emu/citra/assets/18496868/8a30289a-4356-4f3c-b3e3-aa3f7f5f4a7a Texture flickering only occurs when enable _Async Presentation_

Hm to get things right, the issue only occurs when async presentation is enabled and is unaffected by debug renderer (so not a synchronization/race problem) which doesn't print any errors. Do you have any other GPU/system to test with to see if this is AMD specific?

2023-08-14 00:35 UTC, Dragios commented
> > WWE All Stars Graphical Glitch https://github.com/citra-emu/citra/assets/18496868/5d9dfd59-4c06-4528-b11a-e88b02d035eb I have tried to _Enable Debug Renderer_ but it did not display any log when it happens
> > Apologies for poor video quality, have to record externally (cannot reproduce issue when screen record) https://github.com/citra-emu/citra/assets/18496868/8a30289a-4356-4f3c-b3e3-aa3f7f5f4a7a Texture flickering only occurs when enable _Async Presentation_
> 
> Hm to get things right, the issue only occurs when async presentation is enabled and is unaffected by debug renderer (so not a synchronization/race problem) which doesn't print any errors. Do you have any other GPU/system to test with to see if this is AMD specific?

Actually both are separate issue (if you did not notice it earlier). The 1st issue only happens using Vulkan API, irregardless of what setting I try to tinker, it makes no difference.

The second issue only happens when "Async Presentation" is enabled. But I did notice after I restart the emulator, it seems like it no longer occurs even with async presentation on. If I want it to reproduce again, I have to delete the vulkan cache files.
Let me see if I can find other non-AMD system to test, will let you know the result.

2023-08-14 15:02 UTC, vitor-k commented on src/citra_qt/util/vk_device_info.cpp
> +            const QString name = QString::fromLocal8Bit(physical_device.getProperties().deviceName);
Isn't deviceName supposed to be `a null-terminated UTF-8 string`? Shouldn't `QString::fromUtf8` be used in that case?

Also a side note, from Qt5 -> Qt6 it seems like the (const char *str, int size) overload no longer has a default value for size, so this call will probably try to use the QByteArray overload instead, which will [convert](https://doc.qt.io/qt-6/qstring.html#fromLocal8Bit-2) the null bytes to unicode nulls, possibly explaining one behavior reported on discord with invalid characters being shown on the dropdown.

```suggestion
            const QString name = QString::fromUtf8(physical_device.getProperties().deviceName, -1);
```

2023-08-16 13:33 UTC, Dragios commented
> > WWE All Stars Graphical Glitch https://github.com/citra-emu/citra/assets/18496868/5d9dfd59-4c06-4528-b11a-e88b02d035eb I have tried to _Enable Debug Renderer_ but it did not display any log when it happens
> > Apologies for poor video quality, have to record externally (cannot reproduce issue when screen record) https://github.com/citra-emu/citra/assets/18496868/8a30289a-4356-4f3c-b3e3-aa3f7f5f4a7a Texture flickering only occurs when enable _Async Presentation_
> 
> Hm to get things right, the issue only occurs when async presentation is enabled and is unaffected by debug renderer (so not a synchronization/race problem) which doesn't print any errors. Do you have any other GPU/system to test with to see if this is AMD specific?

Seems like it also happens on nVidia platform. The card I'm using is GTX 1650 Ti (mobile)

2023-08-17 06:43 UTC, GPUCode commented
I was able to reproduce flickering issue on AMD cars but not Nvidia. The game itself issues a massive amount of draw calls, I suspect it may be because of overuse of geometry shader. So currently I'm suspecting some missing barrier is causing the flicker

2023-08-20 10:57 UTC, Donel-Bueno commented
I'm facing tons of crashes with custom textures enabled, is this a known issue?

2023-08-20 10:59 UTC, GPUCode commented
> I'm facing tons of crashes with custom textures enabled, is this a known issue?

Custom textures should work with vulkan enabled. Please provide more details such as the game, the pack you are using and the region the crash occurs alongside reproduction steps.

2023-08-20 11:02 UTC, Donel-Bueno commented
https://github.com/citra-emu/citra/pull/6512#issuecomment-1685254802

Thanks for letting me know, I'll do it in a few hours.

2023-08-20 12:49 UTC, DonelBueno commented
It's basically happening in any game I enable custom textures for. Most of them crash at launch (when any custom texture should be loaded).

I did some debugging and noted that the crashes on happens when the rendering resolution is set at 3x or above. After the game is launched, you can then change it to 3x or more (not sure if it is long term stable).

System Specs:

Ryzen 5800x
Geforce GTX 1070 8 GB (Drivers 536.99)
32 GB RAM
Windows 10 Pro x64

2023-08-22 08:25 UTC, DonelBueno commented
@GPUCode Now custom textures crash at launch only when at 5x rendering resolution and above. With OpenGL, though, I can launch them even at 10x.

2023-08-22 08:33 UTC, GPUCode commented
What game/texture pack are you testing?

2023-08-22 10:02 UTC, DonelBueno commented
> What game/texture pack are you testing?

Any game is crashing with custom textures in the conditions I mentioned above. To name a few, Pokémon OR, Zelda ALBW, Zelda OoT, Kid Icarus. If not at launch, shortly after it.

You can test with this pack I made myself (old format): https://community.citra-emu.org/t/pokemon-omega-ruby-alpha-sapphire-hd-texture-pack-19-12-2022/327291

2023-08-23 08:47 UTC, benderscruffy commented
in 2 Fast 4 Gnomz (Europe)
[  33.655363] Render.Vulkan <Critical> video_core/renderer_vulkan/vk_shader_gen_spv.cpp:AppendSource:1281: Unknown source op 8

2023-08-23 09:32 UTC, GPUCode commented
> in 2 Fast 4 Gnomz (Europe) [ 33.655363] Render.Vulkan video_core/renderer_vulkan/vk_shader_gen_spv.cpp:AppendSource:1281: Unknown source op 8

Does this log show in opengl too?

2023-08-24 08:44 UTC, benderscruffy commented
> > in 2 Fast 4 Gnomz (Europe) [ 33.655363] Render.Vulkan video_core/renderer_vulkan/vk_shader_gen_spv.cpp:AppendSource:1281: Unknown source op 8
> 
> Does this log show in opengl too?

yes
[  29.210876] Render.OpenGL <Critical> video_core/renderer_opengl/gl_shader_gen.cpp:AppendSource:378: Unknown source op 8

2023-08-25 04:29 UTC, DonelBueno commented
The latest build fixes my crashes with custom textures and high rendering resolutions, thanks!

2023-08-26 20:30 UTC, theofficialgman commented
build and tested https://github.com/citra-emu/citra-canary/commit/eda6f8d9282efb5b5f216dc0dfe7fcd46a4f6de0 (the latest canary commit as of posting)
Unfortunately I am geting a blank window when playing any game on the Vulkan backend.
No errors in terminal logs

Hardware: nintendo switch (GM20B Maxwell Nvidia GPU)

2023-08-27 03:19 UTC, MPS64 commented
latest canary build crashes with standard resolution.

2023-08-27 03:21 UTC, Dragios commented
> latest canary build crashes with standard resolution.

Clear the shader cache manually and retry.

2023-08-27 03:36 UTC, MPS64 commented
did that, still crashes on launch. should i send a log file?

2023-08-27 05:10 UTC, Dragios commented
> did that, still crashes on launch. should i send a log file?

Yes, you should. 
Try turning on Enable Debug Renderer/Dump Command Buffer as well when sending logs if the current log did not generate any useful info.

2023-08-27 08:00 UTC, MPS64 commented
here's whats in the latest log file. 

[   0.039742] Input <Info> input_common/udp/client.cpp:StartCommunication:206: Starting communication with UDP input server on 127.0.0.1:26760
[   0.121009] Frontend <Info> citra_qt/main.cpp:GMainWindow:231: Citra Version: Canary 2600 | HEAD-eda6f8d
[   0.121021] Frontend <Info> citra_qt/main.cpp:GMainWindow:246: Host CPU: AMD Ryzen 7 4700U with Radeon Graphics          | AVX2 | FMA
[   0.121194] Frontend <Info> citra_qt/main.cpp:GMainWindow:248: Host OS: Windows 11 Version 22H2 (Build 22621.2134)
[   0.121205] Frontend <Info> citra_qt/main.cpp:GMainWindow:251: Host RAM: 15.37 GiB
[   0.121205] Frontend <Info> citra_qt/main.cpp:GMainWindow:252: Host Swap: 15.37 GiB
[   0.203693] HW.AES <Error> core/hw/aes/key.cpp:LoadNativeFirmKeysOld3DS:237: native firm has wrong size 999424
[   0.204472] HW.AES <Error> core/hw/aes/key.cpp:LoadSafeModeNativeFirmKeysOld3DS:296: safe mode native firm has wrong size 995328
[   0.206736] HW.AES <Error> core/hw/aes/key.cpp:LoadPresetKeys:523: Invalid key name generator

2023-08-29 22:52 UTC, theofficialgman commented
I thought I should report, the screen is black on Vulkan backend on latest canary when built with GCC-11 (Ubuntu Jammy default). Building with Clang-14 (Jammy default clang) does not have this issue. That is what I was experiencing here https://github.com/citra-emu/citra/pull/6512#issuecomment-1694496413

another user made me aware of this

2023-09-12 22:28 UTC, merged

2023-09-15 18:32 UTC, askotx commented
I've followed this implementation since 2022-09-22, almost a year and it's finally added!
A big thank you to @GPUCode for making this!