Enable LTO in github actions builds
citra-emu/citra pull request #6609
Opened 2023-06-13 06:37 UTC by Rokkubro

Enables LTO when building in the github actions. Needed some minor changes to get working:

- Windows needs a larger pagefile as otherwise the linking process runs out of memory
- Android needs to use a more recent version of cmake; otherwise it attempts to use the gold linker which is not installed
- Linux builds need to use clang as it can use "ThinLTO" which has much lower memory usage and does not crash in github actions
  - To do this [changes to the build images](https://github.com/citra-emu/build-environments/pull/50) are required

Should squeak out a little bit more performance I wasn't able to see much of a difference in the Windows or AppImage builds but I was getting a couple of frames more on my weaker android phone.

2023-06-14 18:12 UTC, FearlessTobi commented
Please squash your commits into one.

2023-06-14 18:15 UTC, FearlessTobi requested changes
I do not agree with changing compilers, just to use LTO.

Instead we should profile which parts of the code actually benefit from using it and only enable it for them.

2023-06-16 05:30 UTC, Rokkubro commented
> I do not agree with changing compilers, just to use LTO.
> 
> Instead we should profile which parts of the code actually benefit from using it and only enable it for them.

Alright that makes sense. In the meantime, it might be beneficial to enable LTO for the platforms which don't require a change in compiler? Or at least for android as it saw some performance benefits?

2023-06-16 16:30 UTC, SachinVin commented on src/android/app/build.gradle
> +            version "3.26.3+"
3.22.1 is the version provided by android studio and given android's janky interaction with native code I would prefer it to be the one officially supported by android studio

2023-08-14 23:31 UTC, Steveice10 commented
Superseded by https://github.com/citra-emu/citra/issues/6887

2023-08-14 23:31 UTC, closed without merging