yuzu port pull request yuzu-emu/yuzu#9644
citra-emu/citra pull request #6685
Opened 2023-07-10 16:18 UTC by luc-git

This import the a volume button in the status bar

2023-07-13 03:26 UTC, Steveice10 commented on src/citra_qt/configuration/configure_audio.cpp
> +    const float volume = static_cast<float>(
What is this change to float for?

2023-07-13 15:02 UTC, luc-git commented on src/citra_qt/configuration/configure_audio.cpp
> +    const float volume = static_cast<float>(
This is because I used this code with volume up and down shortcuts

2023-07-13 22:27 UTC, FearlessTobi requested changes

2023-07-13 22:27 UTC, FearlessTobi commented on src/citra_qt/main.h
> +    void OnDecreaseVolume();
unused function

2023-07-13 22:27 UTC, FearlessTobi commented on src/citra_qt/main.h
> +    void OnIncreaseVolume();
unused

2023-07-13 22:28 UTC, FearlessTobi commented on src/citra_qt/main.cpp
> +        QPoint bottomLeft = statusBar()->mapToGlobal(rect.topLeft());
```suggestion
        QPoint bottom_left = statusBar()->mapToGlobal(rect.topLeft());
```

2023-07-15 04:48 UTC, Steveice10 commented on src/citra_qt/configuration/configure_audio.cpp
> +    const float volume = static_cast<float>(
The slider currently in the settings menu on nightly seems to be working fine for me. This vlaue is fed to QAbstractSlider::setValue which [takes an int](https://doc.qt.io/qt-6/qabstractslider.html#value-prop), so casting to a float doesn't make any sense to me.

2023-07-15 05:11 UTC, SachinVin commented
Please add screenshots

2023-07-16 20:47 UTC, luc-git commented
https://github.com/citra-emu/citra/assets/102831178/be86d778-4295-40dc-b62b-b932c290517f

2023-07-26 22:38 UTC, SleepingSnakezzz commented
When in-game, updating the volume value in the per-game settings (Emulation>Configure Current Game...) will _not_ update the volume value on the status bar. Only after selecting it, will it update itself. Changing the volume on the global settings (Emulation>Configure) updates it just fine.

2023-07-29 00:38 UTC, luc-git commented
> When in-game, updating the volume value in the per-game settings (Emulation>Configure Current Game...) will _not_ update the volume value on the status bar. Only after selecting it, will it update itself (note, the audio does get updated, only the UI does not). Changing the volume on the global settings (Emulation>Configure) updates it just fine.

Unfortunately I can't fix if I move the volume slider and the volume of the game is set to per game config. When I open pergame settings the volume revert to the value set by the pergame config

2023-08-04 19:16 UTC, Steveice10 commented on src/citra_qt/configuration/configure_per_game.h
> +    Config& game_config_;
Can we merge these two fields into one? I think the passed in existing config would be fine to be a shared pointer or something along those lines.

2023-08-04 19:16 UTC, Steveice10 commented
Requesting review from @GPUCode to look over some of the per game config related stuff.

2023-08-04 21:31 UTC, GPUCode commented
LGTM aside from the duplicated config file. ConfigurePerGame should always open its config file and not take a reference from the main window. There shouldn't be any danger of the same config file being open twice, as the per game config is closed when BootGame returns.

2023-08-04 21:38 UTC, luc-git commented
> LGTM aside from the duplicated config file. ConfigurePerGame should always open its config file and not take a reference from the main window. There shouldn't be any danger of the same config file being open twice, as the per game config is closed when BootGame returns.

I added a reference to make volume slider able to edit volume level while it is set to pergame

2023-08-04 21:39 UTC, luc-git commented
Otherwise it doesn't work and if you open pergame dialog the volume value revert to the old value

2023-08-05 00:21 UTC, GPUCode commented
Can you explain in more detail why that doesn't work?

2023-08-05 23:33 UTC, vitor-k commented
Untagging it for now due to conflicts with other PRs on Canary

2023-08-15 20:03 UTC, luc-git commented
> Can you explain in more detail why that doesn't work?

To reproduce that you just have to set the volume to per-game. Set the volume. Start the game. Set the volume with the volume slider and open the per-game dialog. The volume will be revert back to the value you set through the per-game config. This is the goal of the last commit to fix that

2023-08-15 20:10 UTC, luc-git commented
iirc you juste have to `git reset --hard HEAD^` to index to the second to last commit to test the issue. This issue also happen in yuzu

2023-09-20 08:46 UTC, SleepingSnakezzz commented
@luc-git Since Vulkan is now merged, please resolve conflicts so we can get this into Canary again.

2023-10-09 22:37 UTC, luc-git commented
> @luc-git Since Vulkan is now merged, please resolve conflicts so we can get this into Canary again.

It's fixed

2023-10-11 23:49 UTC, FearlessTobi reviewed
The changes from yuzu look mostly fine, but I don't understand why this is changing the per game config.

2023-10-11 23:49 UTC, FearlessTobi commented on src/citra_qt/configuration/configure_per_game.cpp
> +
```suggestion

```

2023-10-11 23:49 UTC, FearlessTobi commented on src/citra_qt/configuration/configure_per_game.cpp
> +        game_config = std::make_unique<Config>(config_file_name, Config::ConfigType::PerGameConfig);
why is this needed for muting the volume?

2024-01-01 23:51 UTC, Steveice10 commented
Continuing this in https://github.com/citra-emu/citra/pull/7307

2024-01-01 23:51 UTC, closed without merging