Move MiiData to its own namespace and add ChecksummedMiiData
citra-emu/citra pull request #6824
Opened 2023-07-27 22:20 UTC by PabloMK7

This PR moves the `MiiData` struct from the applets namespace to the Mii namespace and to its own file. This was made because the mii format is used by other modules than applets, such as NFC and FRD.

The struct `ChecksummedMiiData` has been added, which appens 4 bytes to the normal `MiiData` struct. This new struct is used in many places too across the system (for example, the nfc code has been adapted to use it). This new struct makes calculating the crc checksum easier.

2023-07-28 00:52 UTC, german77 commented on src/core/hle/service/nfc/nfc_types.h
> -static_assert(std::is_trivial_v<RegisterInfoPrivate>, "RegisterInfoPrivate must be trivial.");
It's necessary for this object to be trivial. Otherwise Module::Interface::SetRegisterInfo won't work.

2023-07-28 15:37 UTC, SachinVin commented on src/core/hle/mii.cpp
> +} // namespace Mii
nit new line. ditto for other files

2023-07-28 15:51 UTC, PabloMK7 commented on src/core/hle/mii.cpp
> +} // namespace Mii
Resolved. I guess you meant new lines at the end of mii.h and mii.cpp

2023-07-28 17:31 UTC, SachinVin commented on src/core/hle/mii.h
> +class MiiData {
Should be a struct

2023-07-28 22:45 UTC, FearlessTobi requested changes

2023-07-28 22:45 UTC, FearlessTobi commented on src/core/hle/mii.cpp
> +u16 ChecksummedMiiData::CalcChecksum() {
```suggestion
u16 ChecksummedMiiData::CalculateChecksum() {
```

2023-07-28 22:45 UTC, FearlessTobi commented on src/core/hle/mii.cpp
> +#include <boost/crc.hpp>
missing copyright headers

2023-07-28 22:45 UTC, FearlessTobi commented on src/core/hle/mii.h
> +#pragma once
same here

2023-07-28 22:45 UTC, FearlessTobi commented on src/core/hle/mii.h
> +        BitField<21, 4, u32> xspacing;
```suggestion
        BitField<21, 4, u32> x_spacing;
```
same with other similar variables

2023-07-28 22:45 UTC, FearlessTobi commented on src/core/hle/mii.h
> +    void FixChecksum() {
seems like this all can be done in CalculateChecksum already

2023-07-29 22:22 UTC, PabloMK7 commented on src/core/hle/mii.h
> +    void FixChecksum() {
What is "this"

2023-07-30 01:03 UTC, FearlessTobi commented on src/core/hle/mii.h
> +    void FixChecksum() {
disregard what i said

2023-07-30 02:16 UTC, Steveice10 commented on src/core/hle/mii.cpp
> +    return boost::crc<16, 0x1021, 0, 0, false, false>(this, offsetof(ChecksummedMiiData, crc16));
Previously the CRC included the 2 bytes between the end of the Mii data and the CRC16 value while this does not, since ```crc16``` was changed to 32-bit to include the 2 extra bytes. Is this still correct?

2023-07-30 11:46 UTC, PabloMK7 commented on src/core/hle/mii.cpp
> +    return boost::crc<16, 0x1021, 0, 0, false, false>(this, offsetof(ChecksummedMiiData, crc16));
Indeed it was not correct. The change was based on official code, but official code uses a weird combination of hardcoded sizes and uses the crc as u32 some times and u16 other times. I just reverted it back to a u16 and made sure the padding is always 0.

2023-07-30 14:17 UTC, Steveice10 approved these changes

2023-07-30 16:16 UTC, FearlessTobi approved these changes

2023-08-01 03:38 UTC, merged