Implement more HTTPC:C functionality
citra-emu/citra pull request #7035
Opened 2023-10-03 14:15 UTC by PabloMK7

This PR implements a lot of missing HTTP:C functionality, which makes it possible for games to download data using it.

The following homebrew/games have been confirmed to be able to use HTTP:C properly:
- FBI to remote install applications.
- CTGP-7 to communicate with its server.
- Friend list to download title icon data.
- Internet Browser to check its own version and to download youtube videos (fails anyways because unimplemented mvd).
- Pokemon Sun/Moon to communicate with the pokemon legality check server.

The following games have partial compatibility:
- Smash Bros can download data such as images and replays, but not upload (missing SendPostData methods).
- Mario Kart 7 cannot upload ghost data (missing SendPostData methods)

This is a first step into fully implementing HTTP:C. Since it makes many games work, I decided to make this PR and implement other functionality in the future.

2023-10-03 17:04 UTC, GPUCode commented
Is the implementation based on disassembly of the httpc service or black box testing?

2023-10-03 17:07 UTC, PabloMK7 commented
Can I get some help on disabling the #warning generated by libressl? Msys2 fails to compile because of it. From what I understand, adding `-Wno-error=#warnings` to the compiler options should change the error back to a warning.

2023-10-03 17:07 UTC, PabloMK7 commented
> Is the implementation based on disassembly of the httpc service or black box testing?

Mostly black box testing, but i looked into the code a bit as well.

2023-10-03 18:07 UTC, Steveice10 commented
> Can I get some help on disabling the #warning generated by libressl? Msys2 fails to compile because of it. From what I understand, adding `-Wno-error=#warnings` to the compiler options should change the error back to a warning.

Make httplib and/or libressl into SYSTEM interfaces similar to some other externals.

2023-10-03 19:50 UTC, GPUCode requested changes

2023-10-03 19:50 UTC, GPUCode commented on src/core/hle/service/http/http_c.cpp
> +        port = is_https ? 443 : 80;
Magic numbers could use a constant

2023-10-03 19:50 UTC, GPUCode commented on src/core/hle/service/http/http_c.cpp
> +static ssize_t write_headers(httplib::Stream& strm,
```suggestion
static ssize_t WriteHeaders(httplib::Stream& strm,
```

2023-10-03 19:50 UTC, GPUCode commented on src/core/hle/service/http/http_c.cpp
> +static std::tuple<std::string, int, std::string, bool> SplitUrl(const std::string& url) {
Return value could be a struct as it has many members

2023-10-03 19:50 UTC, GPUCode commented on src/core/hle/service/http/http_c.cpp
> +static std::tuple<std::string, int, std::string, bool> SplitUrl(const std::string& url) {
Should also add a comment with an example url and how its being split which helps readability.
Also consider if using boost url library would be possible here as its already available in externals

2023-10-03 19:50 UTC, GPUCode commented on src/core/hle/service/http/http_c.cpp
> +    if (itr->second.uses_default_client_cert && !itr->second.clcert_data->init) {
If this never happens on hardware then it should be an assert?

2023-10-03 19:50 UTC, GPUCode commented on src/core/hle/service/http/http_c.cpp
> +    auto itr = contexts.find(context_handle);
contexts.find is repeated a lot in the httpc service. Consider breaking this into a separate function that returns a Context ref/pointer directory which would also make the code cleaner

2023-10-03 19:50 UTC, GPUCode commented on src/core/hle/service/http/http_c.cpp
> +        const std::vector<u8>* header_name;
Can this be ```std::span<const u8>```?

2023-10-03 19:50 UTC, GPUCode commented on src/core/hle/service/http/http_c.cpp
> +    if (client_cert_id != 0x40) {
How was 0x40 derived? Consider adding a comment/constant about it

2023-10-03 19:50 UTC, GPUCode commented on src/core/hle/service/http/http_c.cpp
> +    // Sadly, we have to duplicate code, the class hierarchy in httplib is not very useful...
Can turn the common parts into a lambda if possible

2023-10-03 19:50 UTC, GPUCode commented on src/core/hle/service/http/http_c.cpp
> +    auto header_writter = [&pending_headers](httplib::Stream& strm,
I feel this is too large for a lambda, could probably be a static function instead

2023-10-03 20:05 UTC, DaniElectra commented on src/core/hle/service/http/http_c.cpp
> +    if (itr->second.uses_default_client_cert && !itr->second.clcert_data->init) {
This happens when the ClCertA title (which has the 3DS client ssl keys) can't be found. This title is a system archive, so it would mean that the user hasn't dumped their system files, and I don't think we should assert in that case.

2023-10-03 20:12 UTC, GPUCode commented on src/core/hle/service/http/http_c.cpp
> +    if (itr->second.uses_default_client_cert && !itr->second.clcert_data->init) {
It should show a log message then informing the user of what's missing

2023-10-03 20:18 UTC, GPUCode commented on src/core/hle/service/http/http_c.cpp
> +            while (header_name_str.size() && header_name_str.back() == '\0') {
std::string_view has a constructor that automatically truncates the string, if you can use it in this case

2023-10-04 18:37 UTC, PabloMK7 commented on src/core/hle/service/http/http_c.cpp
> +static std::tuple<std::string, int, std::string, bool> SplitUrl(const std::string& url) {
Boost may not produce the needed fields. This version works as inteneded so no need to remake it.

2023-10-04 18:38 UTC, PabloMK7 commented on src/core/hle/service/http/http_c.cpp
> +    if (itr->second.uses_default_client_cert && !itr->second.clcert_data->init) {
Adding an error

2023-10-04 19:47 UTC, PabloMK7 commented on src/core/hle/service/http/http_c.cpp
> +    if (client_cert_id != 0x40) {
It's the only cert ID, for some reason. It is actually a value not a bitfield.

2023-10-04 19:51 UTC, PabloMK7 commented on src/core/hle/service/http/http_c.cpp
> +    // Sadly, we have to duplicate code, the class hierarchy in httplib is not very useful...
Not really, already tried to not have duplicate code and it wasn't working properly. I have simplified the ifs a bit. There is still some duplicate variables, but making them not be duplicated would make the code less readable.

2023-10-04 19:58 UTC, PabloMK7 commented on src/core/hle/service/http/http_c.cpp
> +            while (header_name_str.size() && header_name_str.back() == '\0') {
There is a constructor that takes a pointer and a size, and a constructor that only taks a pointer and truncates it, but not both at the same time.

2023-10-04 20:04 UTC, GPUCode commented on src/core/hle/service/http/http_c.cpp
> +            while (header_name_str.size() && header_name_str.back() == '\0') {
In that case I suggest turning this into a function TruncateString in common/string_utils.h

2023-10-04 20:13 UTC, DaniElectra commented on src/core/hle/service/http/http_c.cpp
> +                IPC::RequestBuilder rb(ctx, 0x001E, 1, 2);
can we make this consistent?

```suggestion
                IPC::RequestBuilder rb = rp.MakeBuilder(1, 2);
```

same below

2023-10-04 20:13 UTC, DaniElectra commented on src/core/hle/service/http/http_c.cpp
> +                    ctx, static_cast<u16>(ctx.CommandHeader().command_id.Value()), 1, 0);
can we simplify this?

```suggestion
                IPC::RequestBuilder rb = rp.MakeBuilder(1, 0);
```

same below

2023-10-04 20:16 UTC, PabloMK7 commented on src/core/hle/service/http/http_c.cpp
> +                IPC::RequestBuilder rb(ctx, 0x001E, 1, 2);
`rp` is not available in the async context.

2023-10-04 20:17 UTC, PabloMK7 commented on src/core/hle/service/http/http_c.cpp
> +                    ctx, static_cast<u16>(ctx.CommandHeader().command_id.Value()), 1, 0);
Same as above :P

2023-10-04 20:18 UTC, PabloMK7 commented on src/core/hle/service/http/http_c.cpp
> +            while (header_name_str.size() && header_name_str.back() == '\0') {
Are there actually any current uses that would benefit from that?

2023-10-04 20:21 UTC, DaniElectra commented on src/core/hle/service/http/http_c.cpp
> +                    ctx, static_cast<u16>(ctx.CommandHeader().command_id.Value()), 1, 0);
I see. Could we at least make these consistent between them? right now one is using a hardcoded command ID and and another uses the command ID from the context

2023-10-04 20:26 UTC, PabloMK7 commented on src/core/hle/service/http/http_c.cpp
> +                    ctx, static_cast<u16>(ctx.CommandHeader().command_id.Value()), 1, 0);
Sure!

2023-10-04 20:32 UTC, PabloMK7 commented
Took the opportunity to create `HLERequestContext::CommandID()`, as it will be very useful for other `RunAsync` calls in the future.

2023-10-04 20:37 UTC, GPUCode commented on src/core/hle/service/http/http_c.cpp
> +            while (header_name_str.size() && header_name_str.back() == '\0') {
Atm no but I can imagine the spotpass service using this, I saw some similar code over there

2023-10-04 20:39 UTC, PabloMK7 commented on src/core/hle/service/http/http_c.cpp
> +            while (header_name_str.size() && header_name_str.back() == '\0') {
Will do

2023-10-04 20:52 UTC, GPUCode commented on src/core/hle/service/http/http_c.cpp
> +                            const std::vector<Context::RequestHeader>& headers) {
```suggestion
                            std::span<const Context::RequestHeader> headers) {
```

2023-10-04 20:52 UTC, GPUCode commented on src/core/hle/service/http/http_c.cpp
> +    URLInfo url_info = SplitUrl(url.c_str());
Is c_str() necessary? url is already a std::string

2023-10-04 20:52 UTC, GPUCode commented on src/core/hle/service/http/http_c.cpp
> +    // Sadly, we have to duplicate code, the class hierarchy in httplib is not very useful...
Understandable. In that case I would suggest breaking this into a separate member function of Context to make the function more readable if possible

2023-10-04 20:52 UTC, GPUCode commented on src/core/hle/service/http/http_c.cpp
> +    return URLInfo{.is_https = is_https, .host = host, .port = port, .path = path};
```suggestion
    return URLInfo{.is_https = is_https, .host = host, .port = port, .path = path,};
```
This will force clang format to format it properly

2023-10-04 20:55 UTC, GPUCode commented on src/core/hle/service/http/http_c.cpp
> +    async_data->header_name = std::span<const u8>(rp.PopStaticBuffer());
The vector can be implicitly converted to a span

2023-10-04 21:03 UTC, PabloMK7 commented on src/core/hle/service/http/http_c.cpp
> +    // Sadly, we have to duplicate code, the class hierarchy in httplib is not very useful...
I'm not sure about that. How would it be broken? I cannot find a way that would make the code more readable. Keep in mind that it's not possible to return a client instance because `Client` and `SSLClient` are not compatible.

2023-10-04 21:09 UTC, GPUCode commented on src/core/hle/service/http/http_c.cpp
> +    // Sadly, we have to duplicate code, the class hierarchy in httplib is not very useful...
Breaking all code under the is_https if should be feasable into something i.e MakeHttpsRequest

2023-10-04 22:21 UTC, GPUCode commented on src/core/hle/service/http/http_c.cpp
> +static URLInfo SplitUrl(const std::string& url) {
The following implementation on boost should be the same but simpler.
```
static URLInfo SplitUrl(const std::string& url) {
    constexpr u16 default_http_port = 80;
    constexpr u16 default_https_port = 443;

    const auto result = boost::urls::parse_uri(url);
    const bool is_https = result->scheme_id() == boost::urls::scheme::https;
    const auto port = result->port_number();
    const auto default_port = is_https ? default_https_port : default_http_port;
    return URLInfo{
        .is_https = is_https,
        .host = result->encoded_host(),
        .port = port == 0 ? default_port : port,
        .path = result->encoded_path(),
    };
}
```

2023-10-05 11:01 UTC, PabloMK7 commented on src/core/hle/service/http/http_c.cpp
> +    // Sadly, we have to duplicate code, the class hierarchy in httplib is not very useful...
Still not possible, makes the code harder to read bacuse pending headers and url info need to be passed to the new function. Would have to pass lambda to new function.

2023-10-05 12:57 UTC, PabloMK7 commented on src/core/hle/service/http/http_c.cpp
> +    // Sadly, we have to duplicate code, the class hierarchy in httplib is not very useful...
Managed to get something, please take a look

2023-10-05 13:01 UTC, GPUCode commented on src/core/hle/service/http/http_c.cpp
> +    // Sadly, we have to duplicate code, the class hierarchy in httplib is not very useful...
Looks great thanks!

2023-10-05 13:22 UTC, GPUCode approved these changes

2023-10-06 02:52 UTC, Steveice10 commented
Can you resolve the merge conflict with the externals CMakeList change?

2023-10-07 18:18 UTC, FearlessTobi requested changes

2023-10-07 18:18 UTC, FearlessTobi commented on src/core/hle/service/http/http_c.cpp
>      IPC::RequestBuilder rb = rp.MakeBuilder(3, 0);
should have a newline before it

2023-10-07 18:18 UTC, FearlessTobi commented on src/core/hle/kernel/hle_ipc.h
> +    u16 CommandID() const {
Can this be a different PR please?
I would like to keep this consistent in the codebase

2023-10-07 18:18 UTC, FearlessTobi commented on src/core/hle/service/http/http_c.cpp
> +#include <boost/url/src.hpp>
This seems to be unused?
Now that I think about it, it could be used for splitting the url though

2023-10-07 18:18 UTC, FearlessTobi commented on src/core/hle/service/http/http_c.cpp
> +std::shared_ptr<HTTP_C> GetService(Core::System& system) {
this seems to be unused

2023-10-07 18:24 UTC, GPUCode commented on src/core/hle/service/http/http_c.cpp
> +#include <boost/url/src.hpp>
The boost example I provided didn't end up working. The original implementation by Pablo was based on httpc's parsing so its likely better for this specific case

2023-10-07 19:38 UTC, PabloMK7 commented on src/core/hle/service/http/http_c.cpp
> +            const unsigned char* tmp_cert_ptr = clcert_data->certificate.data();
I don't know what you mean.

2023-10-07 19:50 UTC, PabloMK7 commented on src/core/hle/service/http/http_c.cpp
> +        HTTP_C* own;
No idea why I didn't think of it before lol

2023-10-07 19:59 UTC, PabloMK7 commented on src/core/hle/service/http/http_c.cpp
> +#include <boost/url/src.hpp>
boost::replace_all is used in MakeRequest

2023-10-07 20:00 UTC, PabloMK7 commented on src/core/hle/service/http/http_c.cpp
> +std::shared_ptr<HTTP_C> GetService(Core::System& system) {
This is so other modules can access the ClCert data in future PRs. The friends HLE module will need it.

2023-10-07 20:01 UTC, PabloMK7 commented on src/core/hle/service/http/http_c.cpp
> +            const unsigned char* tmp_cert_ptr = clcert_data->certificate.data();
Please check if the changes I made are what you meant and resolve.

2023-10-11 17:09 UTC, merged