Fixed Mali Performance In Open GL and Also Fixed Compile
citra-emu/citra pull request #7141
Opened 2023-11-09 14:23 UTC by Ishan0981

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/citra-emu/citra/7141)

2023-11-09 14:25 UTC, GPUCode commented
The code still does not compile, you need to add the is_mali_gpu member variable

2023-11-09 14:27 UTC, Ishan0981 commented
Ok Wait

2023-11-09 14:46 UTC, SachinVin requested changes

2023-11-09 14:46 UTC, SachinVin commented on src/video_core/renderer_opengl/gl_rasterizer.cpp
> +static bool IsVendorMali() {
Should be `IsVendorArm`, Also this should not be here, it should be in gl_driver

2023-11-09 14:46 UTC, SachinVin commented on src/video_core/renderer_opengl/gl_rasterizer.cpp
> +                                                                          is_mali_gpu ? 525312 : TEXTURE_BUFFER_SIZE} {
What is this magic number?

2023-11-09 14:46 UTC, SachinVin commented on src/video_core/renderer_opengl/gl_rasterizer.cpp
> +      texture_buffer_size{TextureBufferSize()},is_mali_gpu(IsVendorMali()), shader_dirty(true), vertex_buffer{driver, GL_ARRAY_BUFFER,
What is shader_dirty?

2023-11-09 14:49 UTC, SachinVin commented
Have you tested the changes? How much of an improvement is it?

2023-11-09 17:19 UTC, innovation2013 commented
#6375 This PR seems better than what you are doing now！

2023-11-09 17:56 UTC, FearlessTobi commented
Can you also please give a clear explanation of your changes?
Why exactly does this improve performance?

2023-11-09 19:13 UTC, Ishan0981 commented
> The code still does not compile, you need to add the is_mali_gpu member variable

Maybe The Error Is Coming Because I Didn't Write This - #ifdef ARCHITECTURE_ARM64 And #include <string>  If You Can Tell Me Where The Error Is Coming Then I Will Be Helpful

2023-11-10 08:22 UTC, SachinVin commented
This isn't the place for you to start learning C++.
It is inconsiderate and a waste of time to expect others to review changes that _you_ don't even know if they work.
Please do not open PRs if you don't understand what the changes are and what they do.

2023-11-10 08:22 UTC, closed without merging