Stub some missing AM Ticket functions
citra-emu/citra pull request #7172
Opened 2023-11-14 22:39 UTC by PabloMK7

Stubs enough AM functionality so that loading the eShop works, and performing a system update returns an error instead of crashing.

2023-11-15 00:30 UTC, FearlessTobi requested changes

2023-11-15 00:30 UTC, FearlessTobi commented on src/core/hle/service/am/am.cpp
> +
```suggestion
```

2023-11-15 00:30 UTC, FearlessTobi commented on src/core/hle/service/am/am.cpp
> +                                         const u8* buffer) {
can this be a span?

2023-11-15 00:30 UTC, FearlessTobi commented on src/core/hle/service/am/am.cpp
> +    memcpy(data.data() + offset, buffer, length);
```suggestion
    std::memcpy(data.data() + offset, buffer, length);
```

2023-11-15 00:30 UTC, FearlessTobi commented on src/core/hle/service/am/am.cpp
> +        LOG_WARNING(Service_AM, "Discarding ticket for 0x{:016X}.", ticket.GetTitleID());
using #x in the format string, you should be able to remove the manual `0x`

2023-11-15 00:30 UTC, FearlessTobi commented on src/core/hle/service/am/am.cpp
> +    LOG_DEBUG(Service_AM, "(STUBBED) media_type=0x{:02x}", media_type);
```suggestion
    LOG_DEBUG(Service_AM, "(STUBBED) called, media_type=0x{:02x}", media_type);
```

2023-11-15 00:30 UTC, FearlessTobi commented on src/core/hle/service/am/am.cpp
> +    LOG_WARNING(Service_AM, "(STUBBED) ticket_count={}", ticket_count);
```suggestion
    LOG_WARNING(Service_AM, "(STUBBED) called, ticket_count={}", ticket_count);
```

2023-11-15 00:30 UTC, FearlessTobi commented on src/core/hle/service/am/am.cpp
> +    LOG_WARNING(Service_AM, "(STUBBED) media_type={}, filter={}", media_type, filter);
```suggestion
    LOG_WARNING(Service_AM, "(STUBBED) called, media_type={}, filter={}", media_type, filter);
```

2023-11-15 00:30 UTC, FearlessTobi commented on src/core/hle/service/am/am.cpp
> +    LOG_WARNING(Service_AM, "(STUBBED) media_type={}, filter={}", media_type, filter);
```suggestion
    LOG_WARNING(Service_AM, "(STUBBED) called, media_type={}, filter={}", media_type, filter);
```

2023-11-15 00:30 UTC, FearlessTobi commented on src/core/hle/service/am/am.cpp
> +    [[maybe_unused]] u32 count = rp.Pop<u32>();
these can all be const

2023-11-15 00:30 UTC, FearlessTobi commented on src/core/hle/service/am/am.cpp
> +        std::make_shared<Service::FS::File>(am->kernel, std::make_unique<TicketFile>(), path);
shouldn't this work as well?
```suggestion
        std::make_shared<Service::FS::File>(am->kernel, std::make_unique<TicketFile>(), {}});
```

2023-11-15 11:08 UTC, PabloMK7 commented on src/core/hle/service/am/am.cpp
> +                                         const u8* buffer) {
Nope, this is an overriden method from the FileBackend class, would need to change that class method definition as well as all the children classes, which is out of the scope of this PR.

2023-11-17 11:25 UTC, Steveice10 approved these changes

2023-11-18 23:55 UTC, merged