Add random sleep to game main thread on first boot
citra-emu/citra pull request #7199
Opened 2023-11-21 22:20 UTC by PabloMK7

This PR solves two issues:
- Some games seed their randomness with svcGetSystemTick, which is deterministic if the game is boot from the game's list, as the code that seeds the random engine always takes the same amount of cycles to reach. This is solved by sleeping the main game thread a random amount. (On real hardware, this random value corresponds to FS delays and user input delays).
- Some system modules register themselves as available before they have finished initialising, and in citra, system modules and games start at the same time, so weird issues can happen. This is solved by sleeping the booted game main thread about 3 seconds so that system modules have time to initialize themselves (on real hardware, they have plenty of time to initialize before a game is launched).

2023-11-21 22:25 UTC, B3n30 commented
Actually I think a emulator should be deterministic (or should have at least a option to behave in that way). So having a hardcoded random sleep, seems really bad

2023-11-21 22:34 UTC, GPUCode requested changes

2023-11-21 22:34 UTC, GPUCode commented on src/core/core.h
> +    bool main_thread_extended_sleep = false;
This state should be per process and not globally in system

2023-11-21 22:34 UTC, GPUCode commented on src/core/hle/service/service.cpp
> +        const bool has_lle = AttemptLLE(service_module);
AttemptLLE can be changed to return std::shared_ptr<Process> of the spawned LLE process and you can set the sleep flag there

2023-11-21 22:34 UTC, PabloMK7 commented
> Actually I think a emulator should be deterministic (or should have at least a option to behave in that way). So having a hardcoded random sleep, seems really bad

I can add a toggle to disable this actually, but for real user experience, they will prefer actual randomness instead of determinism.

2023-11-21 22:37 UTC, B3n30 commented
It depends. See e.g. the TAS community relies on it. We already have the option to have a fixed system time, so I think the randomness could be tied to that option.

2023-11-21 22:39 UTC, GPUCode commented
Should this also be disabled for when home menu is booted with lle sysmodules?

2023-11-21 22:40 UTC, GPUCode commented on src/core/hle/service/service.cpp
> +        const bool has_lle = AttemptLLE(service_module);
Or better, keep it the way it is, and set the sleep flag inside the function

2023-11-21 22:40 UTC, PabloMK7 commented
> It depends. See e.g. the TAS community relies on it. We already have the option to have a fixed system time, so I think the randomness could be tied to that option.

Yeah indeed, that's the main user base that will benefit from a toggle.

2023-11-21 22:41 UTC, PabloMK7 commented
> Should this also be disabled for when home menu is booted with lle sysmodules?

Home menu also benefits from this, for letting sys modules load.

2023-11-22 00:26 UTC, Steveice10 commented
Leaving point 2 aside for the moment, couldn’t point 1 be solved by just seeding the system tick with a random initial value?

2023-11-22 07:36 UTC, PabloMK7 commented
> Leaving point 2 aside for the moment, couldn’t point 1 be solved by just seeding the system tick with a random initial value?

I tried advancing the clock once and there were issues, maybe I did it wrong tho.

2023-11-22 07:38 UTC, PabloMK7 commented on src/core/core.h
> +    bool main_thread_extended_sleep = false;
I tried, however this flag would need to be set from a non-core project (qt, Android, etc) and I didn't want that. This is a system thing tho, it represents the first app launched in the virtual system, so it made sense to me to place it there.

2023-11-22 07:46 UTC, GPUCode commented on src/core/core.h
> +    bool main_thread_extended_sleep = false;
If you mean the gui toggle you can set a Setting for this from the gui and still have this here.

2023-11-22 07:47 UTC, Steveice10 commented
> I tried advancing the clock once and there were issues, maybe I did it wrong tho.

I think advancing the clock could have side effects, but what just defining an initial value other than 0? Or alternatively, if it's sufficient to solve the random seeding problem, just apply the offset only to the result of svcGetSystemTicks.

2023-11-22 07:56 UTC, GPUCode commented on src/core/core.h
> +    bool main_thread_extended_sleep = false;
To answer the point above, imo this flag affects kernel behavior so System which is meant for more general system functions should not know about kernel implementation details. You don't have to set it for every process, just the main one (should be accessible from system I think?). Putting it in process means you won't have to bring more global state and you won't have to check if it's not an lle process

2023-11-22 13:50 UTC, SachinVin commented
> on real hardware, they have plenty of time to initialize before a game is launched

What does real hardware actually do, is it just a happy coincidence that the services load before the game?

2023-11-22 14:01 UTC, B3n30 commented
For the second bullet point: Why do we do this in this way, we should just register/init the system services first and afterwards start/load the game. This fix seems like trying to fix a symptom instead of fixing the startup order correctly

2023-11-22 19:55 UTC, PabloMK7 commented on src/core/hle/service/service.cpp
> +        const bool has_lle = AttemptLLE(service_module);
Discussed as not possible in discord DMs

2023-11-22 19:57 UTC, PabloMK7 commented
> > on real hardware, they have plenty of time to initialize before a game is launched
> 
> What does real hardware actually do, is it just a happy coincidence that the services load before the game? That just sounds like a race condition then...

Yes... I guess? System modules load first, and due to FS delays, home menu takes about 8 seconds to load. That's way different than 0 milliseconds in citra (as lle modules and games launch at the same time).

2023-11-22 22:11 UTC, GPUCode commented on src/core/hle/kernel/thread.cpp
> +    } else {
```suggestion
    s64 sleep_base_time_ns = 0;
    if (!is_lle_service && Settings::values.delay_main_thread_start) {
```

2023-11-22 22:11 UTC, GPUCode commented on src/core/hle/kernel/kernel.h
> +        return main_thread_extended_sleep;
```suggestion
        return std::exchange(main_thread_extended_sleep, false);
```
Since the flag is always reset after being accessed

2023-11-22 22:11 UTC, GPUCode commented on src/core/hle/service/service.cpp
> +    core.Kernel().SetAppMainThreadExtendedSleep(false);
Are there any cases this would be true, to need an explicit false set?

2023-11-22 22:11 UTC, GPUCode commented on src/core/hle/service/service.cpp
> +        }
```suggestion
        core.Kernel().SetAppMainThreadExtendedSleep(has_lle);
```
Prob faster to avoid the branch since its a simple variable assignment

2023-11-22 22:11 UTC, GPUCode commented on src/core/hle/kernel/kernel.h
> +    bool main_thread_extended_sleep = false;
Might want to add a more detailed comment about why this is needed

2023-11-23 12:15 UTC, Adamillo commented
> This is an issue with LLE system modules, just noticed I didn't mention in the OP.

Well, this sucks. Could we somehow improve the situation on HLE at least?

2023-11-23 16:49 UTC, PabloMK7 commented
> > This is an issue with LLE system modules, just noticed I didn't mention in the OP.
> 
> Well, this sucks. Could we somehow improve the situation on HLE at least?

Not realistically. Would need heuristics to determine if a lle module is ready.

2023-12-13 09:25 UTC, PabloMK7 commented on src/core/hle/kernel/kernel.h
> +        return main_thread_extended_sleep;
I don't like this, the flag is always reset right now, but it may change in the future for any reason. A getter shouldn't be modifying the state, in fact I made it const.

2023-12-13 09:26 UTC, PabloMK7 commented on src/core/hle/service/service.cpp
> +    core.Kernel().SetAppMainThreadExtendedSleep(false);
Most likely not, but better clear the state just in case.

2023-12-13 09:27 UTC, PabloMK7 commented on src/core/hle/service/service.cpp
> +        }
This is not the same behaviour, if a later iteration of the for loop results in has_lle = false, it will be set back from true to false.

2023-12-14 14:24 UTC, GPUCode commented on src/core/hle/kernel/thread.cpp
> +    constexpr const u32 system_module_tid_high = 0x00040130;
```suggestion
    constexpr s64 sleep_random_deviation_ns = 250'000'000LL;
    constexpr s64 sleep_normal_thread_base_ns = 250'000'000LL;
    constexpr s64 sleep_app_thread_base_ns = 2'500'000'000LL;
    constexpr u32 system_module_tid_high = 0x00040130;
```
const is not necessary with constexpr

2024-01-11 16:05 UTC, PabloMK7 commented
> Given that we have a separate solution now for random seeding from ticks, a launch delay would probably be more palatable if we could limit it to only applying when LLE modules are enabled.

Done, changed the UI label to "Delay app main thread start with LLE modules enabled"

2024-01-11 16:36 UTC, Steveice10 commented on src/common/settings.h
> +    Setting<bool> delay_main_thread_start{true, "delay_main_thread_start"};
Move down to the other debug settings, probably this would go right under `lle_modules`. Also if you could add a qualifier to this that it's for LLE modules (maybe something like `delay_start_for_lle_modules`) that might avoid any potential future confusion what this is for. Ditto for updating the name used in the settings logging if you do.

2024-01-11 16:36 UTC, Steveice10 commented on src/core/hle/kernel/thread.cpp
> +        if (kernel.GetAppMainThreadExtendedSleep()) {
nit: This part of the condition doesn't need to be nested, can be part of the previous condition.

2024-01-11 16:36 UTC, Steveice10 commented on src/core/hle/service/service.cpp
> +            core.Kernel().SetAppMainThreadExtendedSleep(true);
nit: Would be good to have a comment explaining what this is for.

2024-01-11 16:36 UTC, Steveice10 commented on src/citra_qt/configuration/configure_debug.ui
> +                <string>Delay app main thread start with LLE modules enabled</string>
Might be more clear with something like `Delay app start for LLE module initialization`? Or if you have a better wording, that would be good as well just as long as it's more clear what it is for.

2024-01-11 17:30 UTC, PabloMK7 commented on src/core/hle/kernel/thread.cpp
> +        if (kernel.GetAppMainThreadExtendedSleep()) {
In fact, this if condition was a bit wrong, fixed it.

2024-01-11 19:04 UTC, Steveice10 approved these changes

2024-01-11 19:04 UTC, Steveice10 commented on src/core/hle/kernel/thread.cpp
> +#include <random>
I don’t think this ‘random’ include is needed anymore.

2024-01-12 20:48 UTC, merged