shader_jit_a64: Use integer-offsets for instruction-labels
citra-emu/citra pull request #7452
Opened 2024-02-18 22:31 UTC by Wunkolo

Oaknut's `Label`-type is pretty big, each label has additional structures for write-backs tracking, causing the instruction_labels array to also be huge for each `JitShader` that gets instantiated. Instead a simple integer-type is used for instruction-offsets from the start of the code-block to allow `JitShader` to be much more compact.

`JitShader` goes from 196840 bytes to 16616.

2024-02-18 22:50 UTC, merryhime commented on src/video_core/shader/shader_jit_a64_compiler.cpp
> +        oaknut::CodeBlock::ptr() + instruction_offsets[instr.flow_control.dest_offset];
`oaknut::CodeBlock::ptr()` is a `u32*` so this is incorrect

2024-02-19 21:32 UTC, merryhime commented on src/video_core/shader/shader_jit_a64_compiler.h
> +                reinterpret_cast<const std::byte*>(oaknut::CodeBlock::ptr() +
`instruction_offsets` now counts `u32`s so this is now incorrect. `reinterpret_cast<std::byte*>(oaknut::CodeBlock::ptr())` is a `std::byte*`

2024-02-19 23:08 UTC, merryhime requested changes

2024-02-19 23:08 UTC, merryhime commented on src/video_core/shader/shader_jit_a64_compiler.cpp
> +    BL(relative_offset);
This is not equivalent because using labels does writeback, and works when the current `instruction_label` is not currently defined.

2024-02-19 23:08 UTC, merryhime commented on src/video_core/shader/shader_jit_a64_compiler.cpp
> +        B(Cond::EQ, relative_offset);
ditto

2024-02-19 23:08 UTC, merryhime commented on src/video_core/shader/shader_jit_a64_compiler.cpp
> +        B(Cond::NE, relative_offset);
ditto

2024-02-20 17:52 UTC, Wunkolo commented
Closing this as this will probably just require a new pattern upstream(something like Xbyak's [LabelManager](https://github.com/herumi/xbyak/blob/63e6ee92cc906a3dbf6b333b2fd51ac1ca95f891/xbyak/xbyak.h#L1428-L1645)?).

2024-02-20 17:52 UTC, closed without merging